/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.JordanRegions
import Mathlib.Topology.Piecewise

/-!
# Gluing the two Schoenflies disks

The geometric part of Moise Chapter 9 constructs compatible extensions on the
closed inside and the closed outside.  This file proves the purely topological
last step: compatible extensions glue to an ambient homeomorphism of the plane.
-/

namespace Schoenflies

open Metric Set Function

namespace JordanCircle

variable (J : JordanCircle)

private theorem carrier_subset_closure_inside : J.carrier ⊆ closure J.inside := by
  rw [J.closure_inside]
  exact subset_union_right

private theorem carrier_subset_closure_outside : J.carrier ⊆ closure J.outside := by
  rw [J.closure_outside]
  exact subset_union_right

theorem compl_closure_inside_subset_outside : (closure J.inside)ᶜ ⊆ J.outside := by
  intro x hx
  have hxCarrier : x ∈ J.carrierᶜ := by
    intro h
    exact hx (J.carrier_subset_closure_inside h)
  rcases J.mem_inside_or_outside hxCarrier with hxI | hxO
  · exact False.elim (hx (subset_closure hxI))
  · exact hxO

theorem compl_closure_outside_subset_inside : (closure J.outside)ᶜ ⊆ J.inside := by
  intro x hx
  have hxCarrier : x ∈ J.carrierᶜ := by
    intro h
    exact hx (J.carrier_subset_closure_outside h)
  rcases J.mem_inside_or_outside hxCarrier with hxI | hxO
  · exact hxI
  · exact False.elim (hx (subset_closure hxO))

theorem closure_compl_closure_inside_subset :
    closure (closure J.inside)ᶜ ⊆ closure J.outside :=
  closure_minimal (J.compl_closure_inside_subset_outside.trans subset_closure) isClosed_closure

theorem closure_compl_closure_outside_subset :
    closure (closure J.outside)ᶜ ⊆ closure J.inside :=
  closure_minimal (J.compl_closure_outside_subset_inside.trans subset_closure) isClosed_closure

theorem frontier_closure_inside_subset_carrier : frontier (closure J.inside) ⊆ J.carrier :=
  frontier_closure_subset.trans (by rw [J.frontier_inside])

theorem frontier_closure_outside_subset_carrier : frontier (closure J.outside) ⊆ J.carrier :=
  frontier_closure_subset.trans (by rw [J.frontier_outside])

end JordanCircle

/-- Data produced by the geometric part of Schoenflies: mutually inverse maps
on both closed complementary regions, agreeing along their common boundary.

The maps are represented on the whole plane because this makes the pasting
lemma independent of subtype coercion.  All meaningful hypotheses are
restricted to the indicated closed regions. -/
structure DiskExtensionData (J : JordanCircle) where
  insideMap : Plane → Plane
  outsideMap : Plane → Plane
  insideInv : Plane → Plane
  outsideInv : Plane → Plane
  continuousOn_insideMap : ContinuousOn insideMap (closure J.inside)
  continuousOn_outsideMap : ContinuousOn outsideMap (closure J.outside)
  continuousOn_insideInv : ContinuousOn insideInv (closedBall (0 : Plane) 1)
  continuousOn_outsideInv : ContinuousOn outsideInv (ball (0 : Plane) 1)ᶜ
  maps_inside : MapsTo insideMap (closure J.inside) (closedBall (0 : Plane) 1)
  maps_inside_open : MapsTo insideMap J.inside (ball (0 : Plane) 1)
  maps_outside : MapsTo outsideMap (closure J.outside) (ball (0 : Plane) 1)ᶜ
  maps_outside_open : MapsTo outsideMap J.outside (closedBall (0 : Plane) 1)ᶜ
  inv_maps_inside : MapsTo insideInv (closedBall (0 : Plane) 1) (closure J.inside)
  inv_maps_inside_open : MapsTo insideInv (ball (0 : Plane) 1) J.inside
  inv_maps_outside : MapsTo outsideInv (ball (0 : Plane) 1)ᶜ (closure J.outside)
  inv_maps_outside_open : MapsTo outsideInv (closedBall (0 : Plane) 1)ᶜ J.outside
  agree_on_curve : EqOn insideMap outsideMap J.carrier
  maps_curve_onto_sphere : insideMap '' J.carrier = sphere (0 : Plane) 1
  inv_agree_on_sphere : EqOn insideInv outsideInv (sphere (0 : Plane) 1)
  left_inside : Set.LeftInvOn insideInv insideMap (closure J.inside)
  left_outside : Set.LeftInvOn outsideInv outsideMap (closure J.outside)
  right_inside : Set.RightInvOn insideInv insideMap (closedBall (0 : Plane) 1)
  right_outside : Set.RightInvOn outsideInv outsideMap (ball (0 : Plane) 1)ᶜ

namespace DiskExtensionData

variable {J : JordanCircle} (E : DiskExtensionData J)

/-- The map obtained by using the inside extension on the closed inside and the
outside extension everywhere else. -/
noncomputable def toFun : Plane → Plane := by
  classical
  exact (closure J.inside).piecewise E.insideMap E.outsideMap

/-- The inverse paste, split along the standard closed disk. -/
noncomputable def invFun : Plane → Plane := by
  classical
  exact (closedBall (0 : Plane) 1).piecewise E.insideInv E.outsideInv

theorem continuous_toFun : Continuous E.toFun := by
  classical
  apply continuous_piecewise
  · intro x hx
    exact E.agree_on_curve (J.frontier_closure_inside_subset_carrier hx)
  · simpa only [isClosed_closure.closure_eq] using E.continuousOn_insideMap
  · exact E.continuousOn_outsideMap.mono J.closure_compl_closure_inside_subset

private theorem frontier_closedBall_eq_sphere :
    frontier (closedBall (0 : Plane) 1) = sphere (0 : Plane) 1 := by
  exact frontier_closedBall (0 : Plane) one_ne_zero

private theorem closure_compl_closedBall_eq :
    closure (closedBall (0 : Plane) 1)ᶜ = (ball (0 : Plane) 1)ᶜ := by
  rw [closure_compl, interior_closedBall (0 : Plane) one_ne_zero]

theorem continuous_invFun : Continuous E.invFun := by
  classical
  apply continuous_piecewise
  · intro x hx
    apply E.inv_agree_on_sphere
    rwa [frontier_closedBall_eq_sphere] at hx
  · simpa only [isClosed_closedBall.closure_eq] using E.continuousOn_insideInv
  · rw [closure_compl_closedBall_eq]
    exact E.continuousOn_outsideInv

theorem left_inv : LeftInverse E.invFun E.toFun := by
  intro x
  classical
  by_cases hx : x ∈ closure J.inside
  · have hy : E.insideMap x ∈ closedBall (0 : Plane) 1 := E.maps_inside hx
    simp only [toFun, invFun, Set.piecewise, hx, hy, if_true]
    exact E.left_inside hx
  · have hxO : x ∈ J.outside := J.compl_closure_inside_subset_outside hx
    have hy : E.outsideMap x ∉ closedBall (0 : Plane) 1 := E.maps_outside_open hxO
    have hxOc : x ∈ closure J.outside := subset_closure hxO
    simp only [toFun, invFun, Set.piecewise, hx, hy, if_false]
    exact E.left_outside hxOc

theorem right_inv : RightInverse E.invFun E.toFun := by
  intro y
  classical
  by_cases hy : y ∈ closedBall (0 : Plane) 1
  · have hx : E.insideInv y ∈ closure J.inside := E.inv_maps_inside hy
    simp only [toFun, invFun, Set.piecewise, hy, hx, if_true]
    exact E.right_inside hy
  · have hyExt : y ∈ (closedBall (0 : Plane) 1)ᶜ := hy
    have hxO : E.outsideInv y ∈ J.outside := E.inv_maps_outside_open hyExt
    have hx : E.outsideInv y ∉ closure J.inside := by
      intro hxi
      rw [J.closure_inside] at hxi
      rcases hxi with hxi | hxi
      · exact J.inside_disjoint_outside.notMem_of_mem_left hxi hxO
      · exact (J.outside_subset_compl hxO) hxi
    have hyClosedExt : y ∈ (ball (0 : Plane) 1)ᶜ := by
      intro hyBall
      exact hy (ball_subset_closedBall hyBall)
    simp only [toFun, invFun, Set.piecewise, hy, hx, if_false]
    exact E.right_outside hyClosedExt

/-- Compatible disk extensions on the two complementary regions give an
ambient homeomorphism of the plane. -/
noncomputable def ambientHomeomorph : Plane ≃ₜ Plane where
  toFun := E.toFun
  invFun := E.invFun
  left_inv := E.left_inv
  right_inv := E.right_inv
  continuous_toFun := E.continuous_toFun
  continuous_invFun := E.continuous_invFun

theorem ambientHomeomorph_apply_curve {x : Plane} (hx : x ∈ J.carrier) :
    E.ambientHomeomorph x = E.insideMap x := by
  classical
  simp [ambientHomeomorph, toFun, J.carrier_subset_closure_inside hx]

theorem ambientHomeomorph_image_carrier :
    E.ambientHomeomorph '' J.carrier = sphere (0 : Plane) 1 := by
  rw [← E.maps_curve_onto_sphere]
  apply image_congr
  intro x hx
  exact E.ambientHomeomorph_apply_curve hx

end DiskExtensionData

end Schoenflies
