/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.InvertedJordanRegions
import Mathlib.Analysis.Convex.GaugeRescale

/-!
# A punctured closed ball is a standard exterior

We first recenter an arbitrary interior puncture by an ambient gauge-rescale
homeomorphism.  A compensating Alexander map restores the original boundary
parametrization, and Euclidean inversion turns the punctured closed ball into
the closed exterior of the unit ball.
-/

namespace Schoenflies

open Metric Set Function Bornology
open LeanEval.Topology.ClassificationOfSurfaces
open LeanEval.Topology.ClassificationOfSurfaces.Moise
open scoped Pointwise

noncomputable section

/-- Gauge rescaling with prescribed source and target interior points. -/
theorem exists_homeomorph_image_eq_apply
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {s t : Set E} (hsc : Convex ℝ s) (hsb : IsVonNBounded ℝ s)
    (htc : Convex ℝ t) (htb : IsVonNBounded ℝ t)
    {x y : E} (hx : x ∈ interior s) (hy : y ∈ interior t) :
    ∃ e : E ≃ₜ E, e x = y ∧
      e '' interior s = interior t ∧
      e '' closure s = closure t ∧ e '' frontier s = frontier t := by
  let h : E ≃ₜ E := by
    apply gaugeRescaleHomeomorph (-x +ᵥ s) (-y +ᵥ t) <;>
      simp [← mem_interior_iff_mem_nhds, interior_vadd,
        mem_vadd_set_iff_neg_vadd_mem, hx, hy, hsc, hsb, htc, htb]
  let e : E ≃ₜ E :=
    (Homeomorph.addLeft (-x)).trans (h.trans (Homeomorph.addLeft y))
  have hzero : h 0 = 0 := by
    dsimp only [h]
    exact gaugeRescale_zero (-x +ᵥ s) (-y +ᵥ t)
  have hexy : e x = y := by
    simpa [e, hzero]
  have hinterior : e '' interior s = interior t := by
    change (fun a => y + h (-x + a)) '' interior s = interior t
    calc
      (fun a => y + h (-x + a)) '' interior s =
          y +ᵥ h '' interior (-x +ᵥ s) := by
        simp_rw [interior_vadd, ← image_vadd, image_image, vadd_eq_add]
      _ = _ := by
        rw [image_gaugeRescaleHomeomorph_interior, interior_vadd,
          vadd_neg_vadd]
  have hclosure : e '' closure s = closure t := by
    change (fun a => y + h (-x + a)) '' closure s = closure t
    calc
      (fun a => y + h (-x + a)) '' closure s =
          y +ᵥ h '' closure (-x +ᵥ s) := by
        simp_rw [closure_vadd, ← image_vadd, image_image, vadd_eq_add]
      _ = _ := by
        rw [image_gaugeRescaleHomeomorph_closure, closure_vadd,
          vadd_neg_vadd]
  have hfrontier : e '' frontier s = frontier t := by
    simp_rw [← closure_sdiff_interior, image_sdiff e.injective,
      hinterior, hclosure]
  exact ⟨e, hexy, hinterior, hclosure, hfrontier⟩

namespace BallPuncture

variable (u : ball (0 : Plane) 1)

/-- An ambient self-homeomorphism preserving the unit ball and sending the
selected interior point to the origin. -/
noncomputable def recenteringAmbient : Plane ≃ₜ Plane :=
  Classical.choose <| exists_homeomorph_image_eq_apply
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (by simpa only [isOpen_ball.interior_eq] using u.2)
    (by simpa only [isOpen_ball.interior_eq] using
      (show (0 : Plane) ∈ ball 0 1 by simp))

theorem recenteringAmbient_apply_point :
    recenteringAmbient u (u : Plane) = 0 :=
  (Classical.choose_spec <| exists_homeomorph_image_eq_apply
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (by simpa only [isOpen_ball.interior_eq] using u.2)
    (by simpa only [isOpen_ball.interior_eq] using
      (show (0 : Plane) ∈ ball 0 1 by simp))).1

theorem recenteringAmbient_image_closedBall :
    recenteringAmbient u '' closedBall (0 : Plane) 1 =
      closedBall (0 : Plane) 1 := by
  have h := (Classical.choose_spec <| exists_homeomorph_image_eq_apply
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (by simpa only [isOpen_ball.interior_eq] using u.2)
    (by simpa only [isOpen_ball.interior_eq] using
      (show (0 : Plane) ∈ ball 0 1 by simp))).2.2.1
  simpa only [recenteringAmbient,
    closure_ball (0 : Plane) (show (1 : ℝ) ≠ 0 by norm_num)] using h

theorem recenteringAmbient_image_sphere :
    recenteringAmbient u '' sphere (0 : Plane) 1 =
      sphere (0 : Plane) 1 := by
  have h := (Classical.choose_spec <| exists_homeomorph_image_eq_apply
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (convex_ball (0 : Plane) 1)
    (NormedSpace.isVonNBounded_ball ℝ Plane 1)
    (by simpa only [isOpen_ball.interior_eq] using u.2)
    (by simpa only [isOpen_ball.interior_eq] using
      (show (0 : Plane) ∈ ball 0 1 by simp))).2.2.2
  simpa only [recenteringAmbient,
    frontier_ball (0 : Plane) (show (1 : ℝ) ≠ 0 by norm_num)] using h

/-- Restriction of the recentering to the closed unit ball. -/
noncomputable def recentering :
    closedBall (0 : Plane) 1 ≃ₜ closedBall (0 : Plane) 1 :=
  ((recenteringAmbient u).image (closedBall (0 : Plane) 1)).trans
    (Homeomorph.setCongr (recenteringAmbient_image_closedBall u))

@[simp] theorem recentering_apply (x : closedBall (0 : Plane) 1) :
    (recentering u x : Plane) = recenteringAmbient u x := rfl

theorem recentering_apply_point :
    recentering u ⟨u, ball_subset_closedBall u.2⟩ =
      ⟨0, by simp⟩ := by
  apply Subtype.ext
  exact recenteringAmbient_apply_point u

/-- Boundary action induced by the recentering. -/
noncomputable def recenteringSphere :
    sphere (0 : Plane) 1 ≃ₜ sphere (0 : Plane) 1 :=
  ((recenteringAmbient u).image (sphere (0 : Plane) 1)).trans
    (Homeomorph.setCongr (recenteringAmbient_image_sphere u))

@[simp] theorem recenteringSphere_apply (x : sphere (0 : Plane) 1) :
    (recenteringSphere u x : Plane) = recenteringAmbient u x := rfl

theorem recentering_boundary (x : sphere (0 : Plane) 1) :
    recentering u ⟨x, sphere_subset_closedBall x.2⟩ =
      ⟨recenteringSphere u x,
        sphere_subset_closedBall (recenteringSphere u x).2⟩ := by
  apply Subtype.ext
  rfl

end BallPuncture

namespace PlaneAlexander

/-- Every Alexander radial extension fixes the origin. -/
  theorem radialHomeomorph_zero
    (h : sphere (0 : Plane) 1 ≃ₜ sphere (0 : Plane) 1) :
    radialHomeomorph h ⟨0, by simp⟩ = ⟨0, by simp⟩ := by
  apply ballToPolygonCell.injective
  rw [radialHomeomorph, Homeomorph.trans_apply,
    Homeomorph.trans_apply, Homeomorph.apply_symm_apply]
  apply PolygonCell.ext
  rw [PolygonCell.radialHomeomorph_apply_val]
  change Circle.radialMap _
      (PolygonalCircle.planeComplexEquiv 0) =
    PolygonalCircle.planeComplexEquiv 0
  simp only [map_zero, Circle.radialMap_zero]

end PlaneAlexander

namespace BallPuncture

/-- Recenter the puncture while cancelling the induced sphere
reparametrization.  This sends the puncture to zero and is the identity on
the boundary sphere. -/
noncomputable def normalizedRecentering (u : ball (0 : Plane) 1) :
    closedBall (0 : Plane) 1 ≃ₜ closedBall (0 : Plane) 1 :=
  (recentering u).trans <|
    PlaneAlexander.radialHomeomorph (recenteringSphere u).symm

theorem normalizedRecentering_apply_point (u : ball (0 : Plane) 1) :
    normalizedRecentering u ⟨u, ball_subset_closedBall u.2⟩ =
      ⟨0, by simp⟩ := by
  rw [normalizedRecentering, Homeomorph.trans_apply,
    recentering_apply_point, PlaneAlexander.radialHomeomorph_zero]

theorem normalizedRecentering_boundary (u : ball (0 : Plane) 1)
    (x : sphere (0 : Plane) 1) :
    normalizedRecentering u ⟨x, sphere_subset_closedBall x.2⟩ =
      ⟨x, sphere_subset_closedBall x.2⟩ := by
  rw [normalizedRecentering, Homeomorph.trans_apply,
    recentering_boundary, PlaneAlexander.radialHomeomorph_ofSphere,
    Homeomorph.symm_apply_apply]

/-- Restrict normalized recentering away from its deleted point. -/
noncomputable def normalizedRecenteringPunctured (u : ball (0 : Plane) 1) :
    {x : closedBall (0 : Plane) 1 // (x : Plane) ≠ (u : Plane)} ≃ₜ
      {x : closedBall (0 : Plane) 1 // (x : Plane) ≠ 0} :=
  (normalizedRecentering u).subtype fun x => by
    constructor
    · intro hxu hzero
      have hEq : normalizedRecentering u x =
          normalizedRecentering u ⟨u, ball_subset_closedBall u.2⟩ := by
        rw [normalizedRecentering_apply_point]
        apply Subtype.ext
        exact hzero
      exact hxu <| congrArg Subtype.val
        ((normalizedRecentering u).injective hEq)
    · intro hzero hxu
      apply hzero
      have hxEq : x = ⟨u, ball_subset_closedBall u.2⟩ := by
        apply Subtype.ext
        exact hxu
      rw [hxEq, normalizedRecentering_apply_point]

end BallPuncture

/-- Inversion identifies the closed unit ball punctured at zero with the
closed exterior of the open unit ball. -/
noncomputable def puncturedClosedBallToExterior :
    {x : closedBall (0 : Plane) 1 // (x : Plane) ≠ 0} ≃ₜ
      ((ball (0 : Plane) 1)ᶜ : Set Plane) where
  toFun x := ⟨EuclideanGeometry.inversion (0 : Plane) 1 x, by
    intro hball
    rw [mem_ball, EuclideanGeometry.dist_inversion_center] at hball
    have hxpos : 0 < dist (x : Plane) 0 := dist_pos.mpr x.2
    have hxle : dist (x : Plane) 0 ≤ 1 := by
      simpa only [mem_closedBall] using x.1.2
    simp only [one_pow] at hball
    have : 1 ≤ 1 / dist (x : Plane) 0 := by
      rw [le_div_iff₀ hxpos]
      simpa using hxle
    exact (not_lt_of_ge this) hball⟩
  invFun y := by
    have hyge : 1 ≤ dist (y : Plane) 0 := by
      apply not_lt.mp
      intro h
      exact y.2 (mem_ball.mpr h)
    have hypos : 0 < dist (y : Plane) 0 := zero_lt_one.trans_le hyge
    have hclosed : EuclideanGeometry.inversion (0 : Plane) 1 y ∈
        closedBall (0 : Plane) 1 := by
      rw [mem_closedBall, EuclideanGeometry.dist_inversion_center]
      simp only [one_pow]
      rw [div_le_iff₀ hypos]
      simpa using hyge
    refine ⟨⟨EuclideanGeometry.inversion (0 : Plane) 1 y, hclosed⟩, ?_⟩
    intro h
    have hy0 : (y : Plane) = 0 :=
      (EuclideanGeometry.inversion_eq_center one_ne_zero).mp h
    exact y.2 <| by rw [hy0]; simp
  left_inv x := by
    apply Subtype.ext
    apply Subtype.ext
    exact EuclideanGeometry.inversion_inversion (0 : Plane) one_ne_zero x
  right_inv y := by
    apply Subtype.ext
    exact EuclideanGeometry.inversion_inversion (0 : Plane) one_ne_zero y
  continuous_toFun := by
    apply continuous_induced_rng.mpr
    exact continuous_const.inversion continuous_const
      (continuous_subtype_val.comp continuous_subtype_val) (fun x => x.2)
  continuous_invFun := by
    apply continuous_induced_rng.mpr
    apply continuous_induced_rng.mpr
    exact continuous_const.inversion continuous_const continuous_subtype_val
      (fun y h => y.2 <| by simpa only [mem_ball, h, dist_self, zero_lt_one])

theorem puncturedClosedBallToExterior_boundary
    (x : sphere (0 : Plane) 1) :
    (puncturedClosedBallToExterior
        ⟨⟨x, sphere_subset_closedBall x.2⟩, by
          intro h; have := x.2; rw [h, mem_sphere, dist_self] at this;
          norm_num at this⟩ : Plane) = x := by
  exact EuclideanGeometry.inversion_of_mem_sphere x.2

end

end Schoenflies
