/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.CyclicLevelAddresses
import Submission.Schoenflies.HairOrdering
import Submission.Schoenflies.LevelEndpointIncidence

/-!
# Endpoint hairs retained between consecutive subdivision levels

Moise's Chapter 9 cells use the old crosscut as one side and the chain of
new crosscuts over its children as the opposite side.  The remaining two
sides lie on the old endpoint hairs.  These lemmas record that the recursive
hair family makes those endpoint hairs literally the same objects at the
two levels.
-/

namespace Schoenflies

open Metric Set Function AffineMap

namespace JordanCircle
namespace InitialAngularArcs

variable {J : JordanCircle}

/-- Transporting an address across an equality of levels does not change its
geometric level arc. -/
theorem levelArc_cast
    (I : J.InitialAngularArcs) {m k : ℕ} (h : m = k)
    (a : LevelAddress m) :
    I.levelArc (_root_.cast (congrArg LevelAddress h) a) = I.levelArc a := by
  subst k
  rfl

/-- The same transport leaves the recursively selected left hair unchanged. -/
theorem levelLeftHair_cast_carrier
    (I : J.InitialAngularArcs) {m k : ℕ} (h : m = k)
    (a : LevelAddress m) :
    (I.levelLeftHair (_root_.cast (congrArg LevelAddress h) a)).carrier =
      (I.levelLeftHair a).carrier := by
  subst k
  rfl

/-- The same transport leaves the recursively selected right hair unchanged. -/
theorem levelRightHair_cast_carrier
    (I : J.InitialAngularArcs) {m k : ℕ} (h : m = k)
    (a : LevelAddress m) :
    (I.levelRightHair (_root_.cast (congrArg LevelAddress h) a)).carrier =
      (I.levelRightHair a).carrier := by
  subst k
  rfl

/-- The leftmost depth-`k` descendant of a level address. -/
def leftmostDescendant {n : ℕ} (a : LevelAddress n) :
    (k : ℕ) → LevelAddress (n + k)
  | 0 => a
  | k + 1 => extendLevelAddress (leftmostDescendant a k) false

/-- The rightmost depth-`k` descendant of a level address. -/
def rightmostDescendant {n : ℕ} (a : LevelAddress n) :
    (k : ℕ) → LevelAddress (n + k)
  | 0 => a
  | k + 1 => extendLevelAddress (rightmostDescendant a k) true

/-- All depth-`k` descendants of one parent, in boundary order. -/
def descendantAddresses {n : ℕ} (a : LevelAddress n) :
    (k : ℕ) → List (LevelAddress (n + k))
  | 0 => [a]
  | k + 1 => refineLevelAddresses (descendantAddresses a k)

theorem descendantAddresses_nonempty {n : ℕ} (a : LevelAddress n) :
    ∀ k : ℕ, descendantAddresses a k ≠ [] := by
  intro k
  induction k with
  | zero => simp [descendantAddresses]
  | succ k ih =>
      cases h : descendantAddresses a k with
      | nil => exact (ih h).elim
      | cons b l => simp [descendantAddresses, refineLevelAddresses, h]

theorem descendantAddresses_nodup {n : ℕ} (a : LevelAddress n) :
    ∀ k : ℕ, (descendantAddresses a k).Nodup := by
  intro k
  induction k with
  | zero => simp [descendantAddresses]
  | succ k ih =>
      exact nodup_refineLevelAddresses (descendantAddresses a k) ih

theorem descendantAddresses_isChain
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n) :
    ∀ k : ℕ, (descendantAddresses a k).IsChain I.LevelAdjacent := by
  intro k
  induction k with
  | zero => simpa [descendantAddresses] using
      (List.isChain_singleton (r := I.LevelAdjacent) a)
  | succ k ih =>
      exact I.isChain_refineLevelAddresses (descendantAddresses a k) ih

theorem descendantAddresses_length {n : ℕ} (a : LevelAddress n) :
    ∀ k : ℕ, (descendantAddresses a k).length = 2 ^ k := by
  intro k
  induction k with
  | zero => simp [descendantAddresses]
  | succ k ih =>
      rw [descendantAddresses, length_refineLevelAddresses, ih, pow_succ]
      exact Nat.mul_comm _ _

/-- Refining every depth-`k` descendant block gives the complete ordered
level at depth `n+k`. -/
theorem flatMap_descendantAddresses_orderedLevelAddresses
    (n k : ℕ) :
    (orderedLevelAddresses n).flatMap
        (fun a => descendantAddresses a k) =
      orderedLevelAddresses (n + k) := by
  induction k with
  | zero => simp [descendantAddresses]
  | succ k ih =>
      change (orderedLevelAddresses n).flatMap
          (fun a => refineLevelAddresses (descendantAddresses a k)) =
        orderedLevelAddresses (n + (k + 1))
      have hrefine :
          (orderedLevelAddresses n).flatMap
              (fun a => refineLevelAddresses (descendantAddresses a k)) =
            refineLevelAddresses
              ((orderedLevelAddresses n).flatMap
                (fun a => descendantAddresses a k)) := by
        simp only [refineLevelAddresses, List.flatMap_assoc]
      rw [hrefine, ih]
      change refineLevelAddresses (orderedLevelAddresses (n + k)) =
        orderedLevelAddresses ((n + k) + 1)
      rw [orderedLevelAddresses]

/-- Descendant blocks of two distinct addresses at the same parent level are
disjoint. -/
theorem descendantAddresses_disjoint_of_ne
    {n k : ℕ} {a b : LevelAddress n} (hab : a ≠ b) :
    List.Disjoint (descendantAddresses a k) (descendantAddresses b k) := by
  have hflat :
      ((orderedLevelAddresses n).flatMap
        (fun c => descendantAddresses c k)).Nodup := by
    rw [flatMap_descendantAddresses_orderedLevelAddresses]
    exact orderedLevelAddresses_nodup (n + k)
  have hpairs := (List.nodup_flatMap.mp hflat).2
  let _ : Std.Symm
      (List.Disjoint on fun c : LevelAddress n => descendantAddresses c k) :=
    { symm := fun _ _ h => h.symm }
  exact hpairs.forall
    (mem_orderedLevelAddresses n a)
    (mem_orderedLevelAddresses n b) hab

@[simp] theorem descendantAddresses_head
    {n : ℕ} (a : LevelAddress n) (k : ℕ) :
    (descendantAddresses a k).head (descendantAddresses_nonempty a k) =
      leftmostDescendant a k := by
  induction k with
  | zero => simp [descendantAddresses, leftmostDescendant]
  | succ k ih =>
      cases h : descendantAddresses a k with
      | nil => exact ((descendantAddresses_nonempty a k) h).elim
      | cons b l =>
          have hb : b = leftmostDescendant a k := by
            simpa [h] using ih
          simp [descendantAddresses, h, leftmostDescendant, hb,
            refineLevelAddresses]

@[simp] theorem descendantAddresses_getLast
    {n : ℕ} (a : LevelAddress n) (k : ℕ) :
    (descendantAddresses a k).getLast (descendantAddresses_nonempty a k) =
      rightmostDescendant a k := by
  induction k with
  | zero => simp [descendantAddresses, rightmostDescendant]
  | succ k ih =>
      cases h : descendantAddresses a k with
      | nil => exact ((descendantAddresses_nonempty a k) h).elim
      | cons b l =>
          have hb : (b :: l).getLast (by simp) =
              rightmostDescendant a k := by
            simpa [h] using ih
          change
            (refineLevelAddresses (descendantAddresses a k)).getLast _ =
              extendLevelAddress (rightmostDescendant a k) true
          simpa only [h, getLast_refineLevelAddresses] using
            congrArg (fun c => extendLevelAddress c true) hb

@[simp] theorem levelArc_leftmostDescendant_left
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n)
    (k : ℕ) :
    (I.levelArc (leftmostDescendant a k)).left =
      (I.levelArc a).left := by
  induction k with
  | zero => rfl
  | succ k ih =>
      simp only [leftmostDescendant,
        I.levelArc_extendLevelAddress_false,
        AccessibleAngularArc.leftChild_left, ih]

@[simp] theorem levelArc_rightmostDescendant_right
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n)
    (k : ℕ) :
    (I.levelArc (rightmostDescendant a k)).right =
      (I.levelArc a).right := by
  induction k with
  | zero => rfl
  | succ k ih =>
      simp only [rightmostDescendant,
        I.levelArc_extendLevelAddress_true,
        AccessibleAngularArc.rightChild_right, ih]

/-- Every listed deeper arc is contained in its parent boundary arc. -/
theorem levelArc_curveArcPlane_subset_of_mem_descendantAddresses
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n) :
    ∀ {k : ℕ} (b : LevelAddress (n + k)),
      b ∈ descendantAddresses a k →
        (I.levelArc b).curveArcPlane ⊆ (I.levelArc a).curveArcPlane := by
  intro k
  induction k with
  | zero =>
      intro b hb
      simp only [descendantAddresses, List.mem_singleton] at hb
      subst b
      exact Subset.rfl
  | succ k ih =>
      intro b hb
      change b ∈ refineLevelAddresses (descendantAddresses a k) at hb
      rw [refineLevelAddresses, List.mem_flatMap] at hb
      obtain ⟨c, hc, hb⟩ := hb
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hb
      rcases hb with rfl | rfl
      · apply (show
            (I.levelArc (extendLevelAddress c false)).curveArcPlane ⊆
              (I.levelArc c).curveArcPlane by
          rw [I.levelArc_extendLevelAddress_false]
          exact (show (I.levelArc c).leftChild.curveArcPlane ⊆
              (I.levelArc c).leftChild.curveArcPlane ∪
                (I.levelArc c).rightChild.curveArcPlane from
            subset_union_left).trans_eq
              (I.levelArc c).leftChild_union_rightChild_curveArcPlane).trans
        exact ih c hc
      · apply (show
            (I.levelArc (extendLevelAddress c true)).curveArcPlane ⊆
              (I.levelArc c).curveArcPlane by
          rw [I.levelArc_extendLevelAddress_true]
          exact (show (I.levelArc c).rightChild.curveArcPlane ⊆
              (I.levelArc c).leftChild.curveArcPlane ∪
                (I.levelArc c).rightChild.curveArcPlane from
            subset_union_right).trans_eq
              (I.levelArc c).leftChild_union_rightChild_curveArcPlane).trans
        exact ih c hc

/-- Every entry of the recursively listed descendants is literally obtained
by a finite descendant word from the parent arc. -/
theorem exists_levelArc_eq_descendant_of_mem_descendantAddresses
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n) :
    ∀ {k : ℕ} (b : LevelAddress (n + k)),
      b ∈ descendantAddresses a k →
        ∃ bs : List Bool,
          I.levelArc b = (I.levelArc a).descendant bs := by
  intro k
  induction k with
  | zero =>
      intro b hb
      simp only [descendantAddresses, List.mem_singleton] at hb
      subst b
      exact ⟨[], rfl⟩
  | succ k ih =>
      intro b hb
      change b ∈ refineLevelAddresses (descendantAddresses a k) at hb
      rw [refineLevelAddresses, List.mem_flatMap] at hb
      obtain ⟨c, hc, hb⟩ := hb
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hb
      obtain ⟨bs, hbs⟩ := ih c hc
      rcases hb with rfl | rfl
      · refine ⟨bs ++ [false], ?_⟩
        rw [I.levelArc_extendLevelAddress_false,
          AccessibleAngularArc.descendant_append, ← hbs]
        rfl
      · refine ⟨bs ++ [true], ?_⟩
        rw [I.levelArc_extendLevelAddress_true,
          AccessibleAngularArc.descendant_append, ← hbs]
        rfl

/-- A listed proper-or-improper descendant's right endpoint never wraps
back to the parent arc's left endpoint. -/
theorem levelArc_right_ne_parent_left_of_mem_descendantAddresses
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n)
    {k : ℕ} (b : LevelAddress (n + k))
    (hb : b ∈ descendantAddresses a k) :
    (J.curvePoint (I.levelArc b).right : Plane) ≠
      (J.curvePoint (I.levelArc a).left : Plane) := by
  obtain ⟨bs, hbs⟩ :=
    I.exists_levelArc_eq_descendant_of_mem_descendantAddresses a b hb
  rw [hbs]
  exact (I.levelArc a).curvePoint_descendant_right_ne_parent_left bs

/-- The left endpoint of a listed descendant likewise never reaches the
parent arc's right endpoint. -/
theorem levelArc_left_ne_parent_right_of_mem_descendantAddresses
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n)
    {k : ℕ} (b : LevelAddress (n + k))
    (hb : b ∈ descendantAddresses a k) :
    (J.curvePoint (I.levelArc b).left : Plane) ≠
      (J.curvePoint (I.levelArc a).right : Plane) := by
  obtain ⟨bs, hbs⟩ :=
    I.exists_levelArc_eq_descendant_of_mem_descendantAddresses a b hb
  rw [hbs]
  exact (I.levelArc a).curvePoint_descendant_left_ne_parent_right bs

/-- The left child retains its parent's left endpoint hair. -/
@[simp] theorem levelLeftHair_extendLevelAddress_false_carrier
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n) :
    (I.levelLeftHair (extendLevelAddress a false)).carrier =
      (I.levelLeftHair a).carrier := by
  let oldMark : I.GenerationMark n :=
    ⟨(J.curvePoint (I.levelArc a).left : Plane),
      I.levelArc_left_mem_generationMarks a⟩
  let childMark : I.GenerationMark (n + 1) :=
    ⟨(J.curvePoint
        (I.levelArc (extendLevelAddress a false)).left : Plane),
      I.levelArc_left_mem_generationMarks (extendLevelAddress a false)⟩
  let retainedMark : I.GenerationMark (n + 1) :=
    ⟨oldMark.1, I.generationMarks_mono n oldMark.2⟩
  have hbase :
      (J.curvePoint
          (I.levelArc (extendLevelAddress a false)).left : Plane) =
        (J.curvePoint (I.levelArc a).left : Plane) := by
    rw [I.levelArc_extendLevelAddress_false,
      AccessibleAngularArc.leftChild_left]
  have hmark : childMark = retainedMark := by
    apply Subtype.ext
    exact hbase
  change ((I.generationInsideHairFamily (n + 1)).hair childMark).carrier =
    ((I.generationInsideHairFamily n).hair oldMark).carrier
  rw [hmark]
  exact congrArg InsideAccessHair.carrier
    (I.generationInsideHairFamily_succ_hair n oldMark)

/-- The extreme left endpoint hair is retained across any finite number of
binary refinements. -/
@[simp] theorem levelLeftHair_leftmostDescendant_carrier
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n)
    (k : ℕ) :
    (I.levelLeftHair (leftmostDescendant a k)).carrier =
      (I.levelLeftHair a).carrier := by
  induction k with
  | zero => rfl
  | succ k ih =>
      rw [leftmostDescendant,
        I.levelLeftHair_extendLevelAddress_false_carrier,
        ih]

/-- The right child retains its parent's right endpoint hair. -/
@[simp] theorem levelRightHair_extendLevelAddress_true_carrier
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n) :
    (I.levelRightHair (extendLevelAddress a true)).carrier =
      (I.levelRightHair a).carrier := by
  let oldMark : I.GenerationMark n :=
    ⟨(J.curvePoint (I.levelArc a).right : Plane),
      I.levelArc_right_mem_generationMarks a⟩
  let childMark : I.GenerationMark (n + 1) :=
    ⟨(J.curvePoint
        (I.levelArc (extendLevelAddress a true)).right : Plane),
      I.levelArc_right_mem_generationMarks (extendLevelAddress a true)⟩
  let retainedMark : I.GenerationMark (n + 1) :=
    ⟨oldMark.1, I.generationMarks_mono n oldMark.2⟩
  have hbase :
      (J.curvePoint
          (I.levelArc (extendLevelAddress a true)).right : Plane) =
        (J.curvePoint (I.levelArc a).right : Plane) := by
    rw [I.levelArc_extendLevelAddress_true,
      AccessibleAngularArc.rightChild_right]
  have hmark : childMark = retainedMark := by
    apply Subtype.ext
    exact hbase
  change ((I.generationInsideHairFamily (n + 1)).hair childMark).carrier =
    ((I.generationInsideHairFamily n).hair oldMark).carrier
  rw [hmark]
  exact congrArg InsideAccessHair.carrier
    (I.generationInsideHairFamily_succ_hair n oldMark)

/-- The extreme right endpoint hair is retained across any finite number of
binary refinements. -/
@[simp] theorem levelRightHair_rightmostDescendant_carrier
    (I : J.InitialAngularArcs) {n : ℕ} (a : LevelAddress n)
    (k : ℕ) :
    (I.levelRightHair (rightmostDescendant a k)).carrier =
      (I.levelRightHair a).carrier := by
  induction k with
  | zero => rfl
  | succ k ih =>
      rw [rightmostDescendant,
        I.levelRightHair_extendLevelAddress_true_carrier,
        ih]

end InitialAngularArcs

namespace InsideAccessHair

variable {J : JordanCircle} {q : Plane}

/-- Distance from the base is the affine hair parameter times the hair
length.  This converts metric collar separation into the order needed to
use the retained hair as an exact polygonal side. -/
theorem dist_base_eq_carrierParameter_mul_dist_tip
    (H : J.InsideAccessHair q) (x : H.carrier) :
    dist q (x : Plane) = H.carrierParameter x * dist q H.tip := by
  rw [← H.lineMap_carrierParameter x]
  simp only [lineMap_apply_module]
  rw [dist_eq_norm, dist_eq_norm]
  have ht0 : 0 ≤ H.carrierParameter x :=
    (H.carrierParameter_mem_Icc x).1
  rw [show q - ((1 - H.carrierParameter x) • q +
      H.carrierParameter x • H.tip) =
      H.carrierParameter x • (q - H.tip) by module]
  rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg ht0]

/-- On a nondegenerate retained hair, being metrically closer to the base is
equivalent to having the smaller affine parameter. -/
theorem carrierParameter_lt_of_dist_base_lt
    (H : J.InsideAccessHair q) (x y : H.carrier)
    (hxy : dist q (x : Plane) < dist q (y : Plane)) :
    H.carrierParameter x < H.carrierParameter y := by
  rw [H.dist_base_eq_carrierParameter_mul_dist_tip x,
    H.dist_base_eq_carrierParameter_mul_dist_tip y] at hxy
  have htip : 0 < dist q H.tip := dist_pos.mpr H.tip_ne_base.symm
  nlinarith

end InsideAccessHair
end JordanCircle

end Schoenflies
