/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.ShrinkingBoundaryConvergence
import Submission.Schoenflies.RegionalExtensions
import Submission.Schoenflies.TopologicalDiskBoundaryExtension

/-!
# Extending the shrinking map across the Jordan carrier

The compatible open homeomorphism is completed on the frontier by the fixed
boundary correspondence from the Jordan carrier to the standard triangle
carrier.  Uniform shrinking of paired Moise cells proves continuity there.
-/

namespace Schoenflies

open Metric Set Function
open LeanEval.Topology.ClassificationOfSurfaces.Moise
open StandardPolygonalCollars

noncomputable section

namespace JordanCircle.InitialAngularArcs

variable {J : JordanCircle} (I : J.InitialAngularArcs)

private theorem boundaryPoint_mem_triangleBody (x : J.carrier) :
    boundaryPoint J x ∈ triangleBody := by
  rw [← standardTriangle_closedRegion,
    standardTriangleCircle.closedRegion_eq_union]
  exact Or.inr (boundaryPoint_mem J x)

/-- The direct-limit inside map with its prescribed value on the Jordan
carrier, regarded as a map of closed planar regions. -/
noncomputable def shrinkingInsideClosureMap (x : closure J.inside) :
    triangleBody := by
  classical
  by_cases hx : (x : Plane) ∈ J.inside
  · exact ⟨I.shrinkingInsideMap ⟨x, hx⟩,
      interior_subset (I.shrinkingInsideMap ⟨x, hx⟩).2⟩
  · have hxc : (x : Plane) ∈ J.carrier := by
      have hxClosure : (x : Plane) ∈ J.inside ∪ J.carrier := by
        rw [← J.closure_inside]
        exact x.property
      exact hxClosure.resolve_left hx
    exact ⟨boundaryPoint J ⟨x, hxc⟩,
      boundaryPoint_mem_triangleBody ⟨x, hxc⟩⟩

@[simp] theorem shrinkingInsideClosureMap_apply_inside (x : J.inside) :
    (I.shrinkingInsideClosureMap ⟨x, subset_closure x.2⟩ : Plane) =
      (I.shrinkingInsideMap x : Plane) := by
  simp only [shrinkingInsideClosureMap, dif_pos x.2]

@[simp] theorem shrinkingInsideClosureMap_apply_carrier (x : J.carrier) :
    (I.shrinkingInsideClosureMap
        ⟨x, by rw [J.closure_inside]; exact Or.inr x.2⟩ : Plane) =
      boundaryPoint J x := by
  have hxNot : (x : Plane) ∉ J.inside := fun hx =>
    (J.inside_subset_compl hx) x.2
  simp only [shrinkingInsideClosureMap, dif_neg hxNot]

/-- Uniform continuity of the prescribed map on the compact Jordan
carrier, in the ambient plane metric. -/
theorem exists_boundaryPoint_dist_lt
    {epsilon : ℝ} (hepsilon : 0 < epsilon) :
    ∃ delta : ℝ, 0 < delta ∧ ∀ x y : J.carrier,
      dist (x : Plane) (y : Plane) < delta →
        dist (boundaryPoint J x) (boundaryPoint J y) < epsilon := by
  letI : CompactSpace J.carrier :=
    isCompact_iff_compactSpace.mp
      (JordanCurve.jordanCurve_isCompact J.parametrization J.continuous)
  let f : J.carrier → Plane := fun x => boundaryPoint J x
  have hf : Continuous f := by
    exact continuous_subtype_val.comp
      (boundaryCarrierHomeomorph J).continuous
  have hu : UniformContinuous f :=
    CompactSpace.uniformContinuous_of_continuous hf
  exact (Metric.uniformContinuous_iff.mp hu) epsilon hepsilon

/-- Continuity of the closed map at a point of the open inside stratum. -/
theorem continuousAt_shrinkingInsideClosureMap_of_mem_inside
    (x : closure J.inside) (hx : (x : Plane) ∈ J.inside) :
    ContinuousAt I.shrinkingInsideClosureMap x := by
  rw [Metric.continuousAt_iff]
  intro epsilon hepsilon
  obtain ⟨deltaMap, hdeltaMap, hmap⟩ :=
    (Metric.continuousAt_iff.mp I.continuous_shrinkingInsideMap.continuousAt)
      epsilon hepsilon
  obtain ⟨deltaOpen, hdeltaOpen, hopen⟩ :=
    Metric.isOpen_iff.mp J.inside_isOpen (x : Plane) hx
  refine ⟨min deltaMap deltaOpen, lt_min hdeltaMap hdeltaOpen, ?_⟩
  intro y hy
  have hyInside : (y : Plane) ∈ J.inside := hopen <| by
    rw [mem_ball]
    exact hy.trans_le (min_le_right _ _)
  let xi : J.inside := ⟨x, hx⟩
  let yi : J.inside := ⟨y, hyInside⟩
  have hxy : dist yi xi < deltaMap :=
    hy.trans_le (min_le_left _ _)
  have h := hmap hxy
  change dist (I.shrinkingInsideClosureMap y : Plane)
      (I.shrinkingInsideClosureMap x : Plane) < epsilon
  have h' : dist (I.shrinkingInsideMap yi : Plane)
      (I.shrinkingInsideMap xi : Plane) < epsilon := by
    change dist (I.shrinkingInsideMap yi : Plane)
      (I.shrinkingInsideMap xi : Plane) < epsilon at h
    exact h
  rw [show (y : closure J.inside) =
      ⟨(yi : Plane), subset_closure yi.2⟩ from Subtype.ext rfl,
    show (x : closure J.inside) =
      ⟨(xi : Plane), subset_closure xi.2⟩ from Subtype.ext rfl,
    I.shrinkingInsideClosureMap_apply_inside,
    I.shrinkingInsideClosureMap_apply_inside]
  exact h'

/-- Continuity of the closed map at a Jordan boundary point. -/
theorem continuousAt_shrinkingInsideClosureMap_of_mem_carrier
    (x : J.carrier) :
    ContinuousAt I.shrinkingInsideClosureMap
      ⟨x, by rw [J.closure_inside]; exact Or.inr x.2⟩ := by
  let xc : closure J.inside :=
    ⟨x, by rw [J.closure_inside]; exact Or.inr x.2⟩
  rw [Metric.continuousAt_iff]
  intro epsilon hepsilon
  obtain ⟨eta, heta, hboundary⟩ :=
    exists_boundaryPoint_dist_lt (J := J) (half_pos hepsilon)
  obtain ⟨N, hpair⟩ := I.eventually_shrinkingBoundaryCell_pair
    (show 0 < eta / 3 by positivity) (half_pos hepsilon)
  have hxNotDisk : (x : Plane) ∉
      (I.shrinkingCompatibleStageSourceDisk N).closedRegion := by
    intro hxDisk
    exact (J.inside_subset_compl
      (I.shrinkingCompatibleStageSourceDisk_closedRegion_subset_inside N hxDisk)) x.2
  obtain ⟨deltaDisk, hdeltaDisk, hdisk⟩ := Metric.isOpen_iff.mp
    (I.shrinkingCompatibleStageSourceDisk N).isCompact_closedRegion.isClosed.isOpen_compl
    (x : Plane) hxNotDisk
  let delta := min deltaDisk (eta / 3)
  refine ⟨delta, lt_min hdeltaDisk (by positivity), ?_⟩
  intro y hy
  change dist (I.shrinkingInsideClosureMap y : Plane)
      (I.shrinkingInsideClosureMap xc : Plane) < epsilon
  have hyx : dist (y : Plane) (x : Plane) < delta := hy
  by_cases hyInside : (y : Plane) ∈ J.inside
  · let yi : J.inside := ⟨y, hyInside⟩
    have hyNotDisk : (yi : Plane) ∉
        (I.shrinkingCompatibleStageSourceDisk N).closedRegion := by
      exact hdisk (by
        rw [mem_ball]
        exact hyx.trans_le (min_le_left _ _))
    obtain ⟨n, hn, a, hyShell, hyCell⟩ :=
      I.exists_shrinkingCompatibleBandCell_of_not_mem_closedRegion N yi hyNotDisk
    obtain ⟨hsource, htarget⟩ :=
      hpair n hn a yi hyShell hyCell
    let p : J.carrier := J.curvePoint (I.levelArc a).left
    have hpx : dist (p : Plane) (x : Plane) < eta := by
      have htriangle : dist (p : Plane) (x : Plane) ≤
          dist (p : Plane) (yi : Plane) +
            dist (yi : Plane) (x : Plane) := dist_triangle _ _ _
      have hsource' : dist (p : Plane) (yi : Plane) ≤ eta / 3 := by
        simpa only [dist_comm] using hsource
      have hyx' : dist (yi : Plane) (x : Plane) < eta / 3 :=
        hyx.trans_le (min_le_right _ _)
      linarith
    have hpBoundary : dist (boundaryPoint J p) (boundaryPoint J x) <
        epsilon / 2 := hboundary p x hpx
    have hmaster : masterPoint (I.levelArc a).left = boundaryPoint J p := by
      symm
      exact boundaryPoint_curvePoint_eq_masterPoint J _
    rw [I.shrinkingInsideClosureMap_apply_carrier]
    have hyEq : (y : closure J.inside) =
        ⟨(yi : Plane), subset_closure yi.2⟩ := Subtype.ext rfl
    rw [hmaster] at htarget
    rw [hyEq, I.shrinkingInsideClosureMap_apply_inside]
    exact (dist_triangle _ (boundaryPoint J p) _).trans_lt (by linarith)
  · have hyCarrier : (y : Plane) ∈ J.carrier := by
      have hyClosure : (y : Plane) ∈ J.inside ∪ J.carrier := by
        rw [← J.closure_inside]
        exact y.property
      exact hyClosure.resolve_left hyInside
    let yc : J.carrier := ⟨y, hyCarrier⟩
    have hyxEta : dist (yc : Plane) (x : Plane) < eta :=
      hyx.trans_le <| (min_le_right _ _).trans (by linarith)
    have hbd := hboundary yc x hyxEta
    have hyEq : (y : closure J.inside) =
        ⟨(yc : Plane), by rw [J.closure_inside]; exact Or.inr yc.2⟩ :=
      Subtype.ext rfl
    rw [hyEq, I.shrinkingInsideClosureMap_apply_carrier,
      I.shrinkingInsideClosureMap_apply_carrier]
    exact hbd.trans (half_lt_self hepsilon)

/-- The shrinking direct-limit map extends continuously to the closed Jordan
inside. -/
theorem continuous_shrinkingInsideClosureMap :
    Continuous I.shrinkingInsideClosureMap := by
  rw [continuous_iff_continuousAt]
  intro x
  by_cases hx : (x : Plane) ∈ J.inside
  · exact I.continuousAt_shrinkingInsideClosureMap_of_mem_inside x hx
  · have hxc : (x : Plane) ∈ J.carrier := by
      have hxClosure : (x : Plane) ∈ J.inside ∪ J.carrier := by
        rw [← J.closure_inside]
        exact x.property
      exact hxClosure.resolve_left hx
    let xc : J.carrier := ⟨x, hxc⟩
    have h := I.continuousAt_shrinkingInsideClosureMap_of_mem_carrier xc
    let x' : closure J.inside :=
      ⟨(xc : Plane), by rw [J.closure_inside]; exact Or.inr xc.2⟩
    have hxx' : x = x' := Subtype.ext rfl
    rw [hxx']
    exact h

private theorem mem_standardTriangleInterior_of_mem_triangleInterior
    {z : Plane} (hz : z ∈ interior triangleBody) :
    z ∈ standardTriangleCircle.interiorRegion := by
  rw [← standardTriangleCircle.interior_closedRegion,
    standardTriangle_closedRegion]
  exact hz

private theorem mem_triangleInterior_of_mem_standardTriangleInterior
    {z : Plane} (hz : z ∈ standardTriangleCircle.interiorRegion) :
    z ∈ interior triangleBody := by
  rw [← standardTriangle_closedRegion,
    standardTriangleCircle.interior_closedRegion]
  exact hz

/-- The closed extension is injective: it is injective on each stratum, and
the open triangle interior is disjoint from its polygonal carrier. -/
theorem injective_shrinkingInsideClosureMap :
    Injective I.shrinkingInsideClosureMap := by
  intro x y hxy
  by_cases hx : (x : Plane) ∈ J.inside
  · by_cases hy : (y : Plane) ∈ J.inside
    · let xi : J.inside := ⟨x, hx⟩
      let yi : J.inside := ⟨y, hy⟩
      have hmap : I.shrinkingInsideMap xi = I.shrinkingInsideMap yi := by
        apply Subtype.ext
        have hval := congrArg Subtype.val hxy
        rw [show x = ⟨(xi : Plane), subset_closure xi.2⟩ from Subtype.ext rfl,
          show y = ⟨(yi : Plane), subset_closure yi.2⟩ from Subtype.ext rfl,
          I.shrinkingInsideClosureMap_apply_inside,
          I.shrinkingInsideClosureMap_apply_inside] at hval
        exact hval
      have hxyi := I.shrinkingInsideHomeomorph.injective hmap
      apply Subtype.ext
      exact congrArg (fun z : J.inside => (z : Plane)) hxyi
    · have hyCarrier : (y : Plane) ∈ J.carrier := by
        have hyClosure : (y : Plane) ∈ J.inside ∪ J.carrier := by
          rw [← J.closure_inside]
          exact y.property
        exact hyClosure.resolve_left hy
      let xi : J.inside := ⟨x, hx⟩
      let yc : J.carrier := ⟨y, hyCarrier⟩
      have hval := congrArg Subtype.val hxy
      rw [show x = ⟨(xi : Plane), subset_closure xi.2⟩ from Subtype.ext rfl,
        show y = ⟨(yc : Plane), by
          rw [J.closure_inside]; exact Or.inr yc.2⟩ from Subtype.ext rfl,
        I.shrinkingInsideClosureMap_apply_inside,
        I.shrinkingInsideClosureMap_apply_carrier] at hval
      have hxInterior : (I.shrinkingInsideMap xi : Plane) ∈
          standardTriangleCircle.interiorRegion :=
        mem_standardTriangleInterior_of_mem_triangleInterior
          (I.shrinkingInsideMap xi).2
      exact False.elim <| Set.disjoint_left.mp
        (PolygonalCircle.carrier_disjoint_interiorRegion standardTriangleCircle)
        (hval ▸ boundaryPoint_mem J yc) hxInterior
  · have hxCarrier : (x : Plane) ∈ J.carrier := by
      have hxClosure : (x : Plane) ∈ J.inside ∪ J.carrier := by
        rw [← J.closure_inside]
        exact x.property
      exact hxClosure.resolve_left hx
    by_cases hy : (y : Plane) ∈ J.inside
    · let xc : J.carrier := ⟨x, hxCarrier⟩
      let yi : J.inside := ⟨y, hy⟩
      have hval := congrArg Subtype.val hxy
      rw [show x = ⟨(xc : Plane), by
          rw [J.closure_inside]; exact Or.inr xc.2⟩ from Subtype.ext rfl,
        show y = ⟨(yi : Plane), subset_closure yi.2⟩ from Subtype.ext rfl,
        I.shrinkingInsideClosureMap_apply_carrier,
        I.shrinkingInsideClosureMap_apply_inside] at hval
      have hyInterior : (I.shrinkingInsideMap yi : Plane) ∈
          standardTriangleCircle.interiorRegion :=
        mem_standardTriangleInterior_of_mem_triangleInterior
          (I.shrinkingInsideMap yi).2
      exact False.elim <| Set.disjoint_left.mp
        (PolygonalCircle.carrier_disjoint_interiorRegion standardTriangleCircle)
        (boundaryPoint_mem J xc) (hval ▸ hyInterior)
    · have hyCarrier : (y : Plane) ∈ J.carrier := by
        have hyClosure : (y : Plane) ∈ J.inside ∪ J.carrier := by
          rw [← J.closure_inside]
          exact y.property
        exact hyClosure.resolve_left hy
      let xc : J.carrier := ⟨x, hxCarrier⟩
      let yc : J.carrier := ⟨y, hyCarrier⟩
      have hval := congrArg Subtype.val hxy
      rw [show x = ⟨(xc : Plane), by
          rw [J.closure_inside]; exact Or.inr xc.2⟩ from Subtype.ext rfl,
        show y = ⟨(yc : Plane), by
          rw [J.closure_inside]; exact Or.inr yc.2⟩ from Subtype.ext rfl,
        I.shrinkingInsideClosureMap_apply_carrier,
        I.shrinkingInsideClosureMap_apply_carrier] at hval
      have hxyc : xc = yc := boundaryPoint_injective J hval
      apply Subtype.ext
      exact congrArg (fun z : J.carrier => (z : Plane)) hxyc

/-- Every point of the closed standard triangle is either reached by the
open direct-limit inverse or by the prescribed carrier homeomorphism. -/
theorem surjective_shrinkingInsideClosureMap :
    Surjective I.shrinkingInsideClosureMap := by
  intro z
  have hzLayers : (z : Plane) ∈
      standardTriangleCircle.interiorRegion ∪
        standardTriangleCircle.carrier := by
    rw [← standardTriangleCircle.closedRegion_eq_union,
      standardTriangle_closedRegion]
    exact z.2
  rcases hzLayers with hzInterior | hzCarrier
  · let zi : interior triangleBody :=
      ⟨z, mem_triangleInterior_of_mem_standardTriangleInterior hzInterior⟩
    let xi : J.inside := I.shrinkingInsideHomeomorph.symm zi
    let x : closure J.inside := ⟨xi, subset_closure xi.2⟩
    refine ⟨x, ?_⟩
    apply Subtype.ext
    rw [show x = ⟨(xi : Plane), subset_closure xi.2⟩ from rfl,
      I.shrinkingInsideClosureMap_apply_inside]
    exact congrArg Subtype.val
      (I.shrinkingInsideHomeomorph.apply_symm_apply zi)
  · let zc : standardTriangleCircle.carrier := ⟨z, hzCarrier⟩
    let xc : J.carrier := (boundaryCarrierHomeomorph J).symm zc
    let x : closure J.inside :=
      ⟨xc, by rw [J.closure_inside]; exact Or.inr xc.2⟩
    refine ⟨x, ?_⟩
    apply Subtype.ext
    rw [show x = ⟨(xc : Plane), by
        rw [J.closure_inside]; exact Or.inr xc.2⟩ from rfl,
      I.shrinkingInsideClosureMap_apply_carrier,
      ← boundaryCarrierHomeomorph_apply]
    exact congrArg Subtype.val
      ((boundaryCarrierHomeomorph J).apply_symm_apply zc)

/-- The shrinking construction gives a homeomorphism from the closed bounded
Jordan region to the closed standard triangle. -/
noncomputable def shrinkingInsideClosureHomeomorph :
    closure J.inside ≃ₜ triangleBody := by
  letI : CompactSpace (closure J.inside) :=
    isCompact_iff_compactSpace.mp <|
      Metric.isCompact_of_isClosed_isBounded isClosed_closure
        J.inside_bounded.closure
  let e : closure J.inside ≃ triangleBody :=
    Equiv.ofBijective I.shrinkingInsideClosureMap
      ⟨I.injective_shrinkingInsideClosureMap,
        I.surjective_shrinkingInsideClosureMap⟩
  exact Continuous.homeoOfEquivCompactToT2
    (f := e) I.continuous_shrinkingInsideClosureMap

@[simp] theorem shrinkingInsideClosureHomeomorph_apply (x : closure J.inside) :
    I.shrinkingInsideClosureHomeomorph x = I.shrinkingInsideClosureMap x := by
  rfl

/-- Identify the closed standard triangle with the unit ball using the
existing polygonal disk straightening. -/
noncomputable def triangleBodyToBall :
    triangleBody ≃ₜ closedBall (0 : Plane) 1 :=
  (Homeomorph.setCongr standardTriangle_closedRegion.symm).trans
    (PolygonalCircle.closedRegionToBall standardTriangleCircle)

theorem triangleBodyToBall_boundary
    (p : standardTriangleCircle.carrier) :
    triangleBodyToBall
        ⟨p, by
          rw [← standardTriangle_closedRegion,
            standardTriangleCircle.closedRegion_eq_union]
          exact Or.inr p.2⟩ =
      ⟨PolygonalCircle.carrierToSphere standardTriangleCircle p,
        sphere_subset_closedBall
          (PolygonalCircle.carrierToSphere standardTriangleCircle p).2⟩ := by
  change PolygonalCircle.closedRegionToBall standardTriangleCircle
      ⟨p, by
        rw [standardTriangleCircle.closedRegion_eq_union]
        exact Or.inr p.2⟩ = _
  exact PolygonalCircle.closedRegionToBall_boundary standardTriangleCircle p

/-- Correct the arbitrary boundary parametrization chosen by the polygonal
disk straightening to the exact sphere parametrization required by the
Schoenflies statement. -/
noncomputable def insideSphereBoundaryCorrection (J : JordanCircle) :
    sphere (0 : Plane) 1 ≃ₜ sphere (0 : Plane) 1 :=
  (PolygonalCircle.carrierToSphere standardTriangleCircle).symm.trans <|
    (boundaryCarrierHomeomorph J).symm.trans J.carrierHomeomorph.symm

@[simp] theorem insideSphereBoundaryCorrection_apply (x : J.carrier) :
    insideSphereBoundaryCorrection J
        (PolygonalCircle.carrierToSphere standardTriangleCircle
          (boundaryCarrierHomeomorph J x)) =
      J.carrierHomeomorph.symm x := by
  simp only [insideSphereBoundaryCorrection, Homeomorph.trans_apply,
    Homeomorph.symm_apply_apply]

/-- The completed bounded-side homeomorphism, now with the exact prescribed
unit-sphere boundary values. -/
noncomputable def shrinkingInsideBallHomeomorph :
    closure J.inside ≃ₜ closedBall (0 : Plane) 1 :=
  I.shrinkingInsideClosureHomeomorph |>.trans <|
    triangleBodyToBall.trans <|
      PlaneAlexander.radialHomeomorph (insideSphereBoundaryCorrection J)

theorem shrinkingInsideBallHomeomorph_boundary (x : J.carrier) :
    (I.shrinkingInsideBallHomeomorph
        ⟨x, by rw [J.closure_inside]; exact Or.inr x.2⟩ : Plane) =
      (J.carrierHomeomorph.symm x : Plane) := by
  let xc : closure J.inside :=
    ⟨x, by rw [J.closure_inside]; exact Or.inr x.2⟩
  let p : standardTriangleCircle.carrier := boundaryCarrierHomeomorph J x
  have hclosure : I.shrinkingInsideClosureHomeomorph xc =
      ⟨p, by
        rw [← standardTriangle_closedRegion,
          standardTriangleCircle.closedRegion_eq_union]
        exact Or.inr p.2⟩ := by
    apply Subtype.ext
    rw [I.shrinkingInsideClosureHomeomorph_apply]
    exact (I.shrinkingInsideClosureMap_apply_carrier x).trans
      (boundaryCarrierHomeomorph_apply J x).symm
  change (PlaneAlexander.radialHomeomorph (insideSphereBoundaryCorrection J)
      (triangleBodyToBall (I.shrinkingInsideClosureHomeomorph xc)) : Plane) = _
  rw [hclosure, triangleBodyToBall_boundary,
    PlaneAlexander.radialHomeomorph_ofSphere,
    insideSphereBoundaryCorrection_apply]

/-- Moise's bounded-side, or first-form, Schoenflies theorem. -/
noncomputable def shrinkingInsideRegionalExtensionData :
    InsideRegionalExtensionData J where
  homeomorph := I.shrinkingInsideBallHomeomorph
  boundary := I.shrinkingInsideBallHomeomorph_boundary

end JordanCircle.InitialAngularArcs

end

end Schoenflies
