/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.JordanRegions

/-!
# Metric bounds for Jordan regions

The bounded complementary component of a Jordan circle lies in every closed
ball which contains the circle.  This is the non-polygonal counterpart of the
corresponding Moise lemma for polygonal circles and lets metric control of a
collar-cell boundary control the whole cell.
-/

namespace Schoenflies

open Metric Set Function Bornology

namespace JordanCircle

/-- The bounded Jordan region lies in every closed ball containing its
boundary. -/
theorem closure_inside_subset_closedBall_of_carrier_subset
    (J : JordanCircle) {c : Plane} {r : ℝ}
    (hcarrier : J.carrier ⊆ closedBall c r) :
    closure J.inside ⊆ closedBall c r := by
  have hr : 0 ≤ r := by
    obtain ⟨z, hz⟩ : (sphere (0 : Plane) 1).Nonempty :=
      NormedSpace.sphere_nonempty.mpr zero_le_one
    have hpoint : J.parametrization ⟨z, hz⟩ ∈ J.carrier :=
      ⟨⟨z, hz⟩, rfl⟩
    have hv := hcarrier hpoint
    exact dist_nonneg.trans (mem_closedBall.mp hv)
  have hinterior : J.inside ⊆ closedBall c r := by
    intro x hx
    rw [mem_closedBall]
    by_contra hnot
    have hdist : r < dist x c := lt_of_not_ge hnot
    let line : ℝ →ᵃ[ℝ] Plane := AffineMap.lineMap c x
    let ray : Set Plane := line '' Ici (1 : ℝ)
    have hxRay : x ∈ ray := by
      refine ⟨1, mem_Ici.mpr le_rfl, ?_⟩
      simp [line]
    have hrayPreconnected : IsPreconnected ray := by
      have hlineContinuous : ContinuousOn line (Ici (1 : ℝ)) :=
        line.continuous_of_finiteDimensional.continuousOn
      exact (convex_Ici (1 : ℝ)).isPreconnected.image line hlineContinuous
    have hrayOff : ray ⊆ J.carrierᶜ := by
      rintro y ⟨t, ht, rfl⟩ hyCarrier
      have hyt := hcarrier hyCarrier
      rw [mem_closedBall] at hyt
      have ht0 : 0 ≤ t := le_trans (by norm_num) ht
      have hdformula : dist (AffineMap.lineMap c x t) c =
          t * dist x c := by
        rw [dist_lineMap_left, Real.norm_eq_abs, abs_of_nonneg ht0,
          dist_comm c x]
      rw [hdformula] at hyt
      have hdle : dist x c ≤ t * dist x c := by
        simpa using mul_le_mul_of_nonneg_right ht dist_nonneg
      exact (not_lt_of_ge (hdle.trans hyt)) hdist
    have hraySplit : ray ⊆ J.inside ∪ J.outside := by
      rw [J.inside_union_outside]
      exact hrayOff
    have hrayInside : ray ⊆ J.inside :=
      hrayPreconnected.subset_left_of_subset_union
        J.inside_isOpen J.outside_isOpen J.inside_disjoint_outside
        hraySplit ⟨x, hxRay, hx⟩
    obtain ⟨R, hR⟩ := J.inside_bounded.subset_closedBall c
    let d := dist x c
    have hd : 0 < d := lt_of_le_of_lt hr hdist
    let t : ℝ := (|R| + 1) / d + 1
    have ht : 1 ≤ t := by
      dsimp [t]
      have : 0 ≤ (|R| + 1) / d := div_nonneg (by positivity) hd.le
      linarith
    let y := AffineMap.lineMap c x t
    have hyRay : y ∈ ray := ⟨t, mem_Ici.mpr ht, rfl⟩
    have hyBound := hR (hrayInside hyRay)
    rw [mem_closedBall] at hyBound
    have hydist : dist y c = t * d := by
      dsimp [y, d]
      rw [dist_lineMap_left, Real.norm_eq_abs,
        abs_of_nonneg (le_trans (by norm_num) ht), dist_comm c x]
    rw [hydist] at hyBound
    have hRabs : R ≤ |R| := le_abs_self R
    dsimp [t] at hyBound
    field_simp [hd.ne'] at hyBound
    nlinarith
  rw [J.closure_inside]
  exact union_subset hinterior hcarrier

end JordanCircle

end Schoenflies
