/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.HairOrdering
import Submission.Schoenflies.TrimmedCollarCells

/-!
# Synchronizing neighboring level joins on a retained hair

Independently selected controlled joins need not initially end at the same
point of their common retained access hair.  Following Moise 9.6, choose the
shallower of the two points.  Exactly one join then needs a nondegenerate
extension along the hair, and that extension meets the boundary-side hair
segment only at the synchronized point.
-/

namespace Schoenflies

open Metric Set Function

namespace JordanCircle
namespace InitialAngularArcs

variable {J : JordanCircle} {I : J.InitialAngularArcs}

/-- Level endpoint hairs are literally selected from the same retained
finite family whenever their plane anchors agree. -/
theorem levelRightHair_carrier_eq_levelLeftHair_of_eq
    {n : ℕ} (a b : LevelAddress n)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    (I.levelRightHair a).carrier = (I.levelLeftHair b).carrier := by
  let ir : I.GenerationMark n :=
    ⟨(J.curvePoint (I.levelArc a).right : Plane),
      I.levelArc_right_mem_generationMarks a⟩
  let il : I.GenerationMark n :=
    ⟨(J.curvePoint (I.levelArc b).left : Plane),
      I.levelArc_left_mem_generationMarks b⟩
  have hir : ir = il := Subtype.ext hshared
  change ((I.generationInsideHairFamily n).hair ir).carrier =
    ((I.generationInsideHairFamily n).hair il).carrier
  rw [hir]

namespace LevelInsideJoinData

variable {n : ℕ} {a b : LevelAddress n}
  {epsilon : ℝ} {hepsilon : 0 < epsilon}

/-- Trimming against a shortened hair still leaves the endpoint on the
underlying retained generation hair. -/
theorem trimmedRightPoint_mem_levelRightHair
    (D : I.LevelInsideJoinData a epsilon hepsilon) :
    D.trimmedRightPoint ∈ (I.levelRightHair a).carrier :=
  (I.levelRightHair a).shortenToOpen_carrier_subset
    Metric.isOpen_thickening
    (self_subset_thickening hepsilon _
      (I.levelArc a).right_mem_curveArcPlane)
    D.trimmedRightPoint_mem

theorem trimmedLeftPoint_mem_levelLeftHair
    (D : I.LevelInsideJoinData a epsilon hepsilon) :
    D.trimmedLeftPoint ∈ (I.levelLeftHair a).carrier :=
  (I.levelLeftHair a).shortenToOpen_carrier_subset
    Metric.isOpen_thickening
    (self_subset_thickening hepsilon _
      (I.levelArc a).left_mem_curveArcPlane)
    D.trimmedLeftPoint_mem

theorem trimmedRightPoint_inside
    (D : I.LevelInsideJoinData a epsilon hepsilon) :
    D.trimmedRightPoint ∈ J.inside :=
  (D.range_trimmedLinePath_subset_controlled
    (Path.source_mem_range D.trimmedLinePath)).1

theorem trimmedLeftPoint_inside
    (D : I.LevelInsideJoinData a epsilon hepsilon) :
    D.trimmedLeftPoint ∈ J.inside :=
  (D.range_trimmedLinePath_subset_controlled
    (Path.target_mem_range D.trimmedLinePath)).1

/-- Regard the right trimmed endpoint as a point of its retained hair. -/
noncomputable def rightHairPoint
    (D : I.LevelInsideJoinData a epsilon hepsilon) :
    (I.levelRightHair a).carrier :=
  ⟨D.trimmedRightPoint, D.trimmedRightPoint_mem_levelRightHair⟩

/-- Transport the neighboring left trimmed endpoint onto the same retained
hair, using equality of their boundary anchors. -/
noncomputable def adjacentLeftHairPoint
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    (I.levelRightHair a).carrier :=
  ⟨E.trimmedLeftPoint, by
    rw [I.levelRightHair_carrier_eq_levelLeftHair_of_eq a b hshared]
    exact E.trimmedLeftPoint_mem_levelLeftHair⟩

/-- The common point used after synchronizing two neighboring joins is the
shallower of their independently selected endpoints. -/
noncomputable def synchronizedPoint
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) : Plane :=
  ((I.levelRightHair a).shallowerPoint D.rightHairPoint
    (E.adjacentLeftHairPoint hshared) :
      (I.levelRightHair a).carrier)

theorem synchronizedPoint_eq_right_or_left
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    D.synchronizedPoint E hshared = D.trimmedRightPoint ∨
      D.synchronizedPoint E hshared = E.trimmedLeftPoint := by
  have h := (I.levelRightHair a).shallowerPoint_eq_left_or_right
    D.rightHairPoint (E.adjacentLeftHairPoint hshared)
  exact h.imp (congrArg Subtype.val) (congrArg Subtype.val)

theorem synchronizedPoint_mem_levelRightHair
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    D.synchronizedPoint E hshared ∈ (I.levelRightHair a).carrier :=
  ((I.levelRightHair a).shallowerPoint D.rightHairPoint
    (E.adjacentLeftHairPoint hshared)).2

theorem synchronizedPoint_mem_levelLeftHair
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    D.synchronizedPoint E hshared ∈ (I.levelLeftHair b).carrier := by
  rw [← I.levelRightHair_carrier_eq_levelLeftHair_of_eq a b hshared]
  exact D.synchronizedPoint_mem_levelRightHair E hshared

theorem synchronizedPoint_inside
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    D.synchronizedPoint E hshared ∈ J.inside := by
  rcases D.synchronizedPoint_eq_right_or_left E hshared with h | h
  · simpa [h] using D.trimmedRightPoint_inside
  · simpa [h] using E.trimmedLeftPoint_inside

theorem synchronizedPoint_parameter_le_right
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    (I.levelRightHair a).carrierParameter
        ⟨D.synchronizedPoint E hshared,
          D.synchronizedPoint_mem_levelRightHair E hshared⟩ ≤
      (I.levelRightHair a).carrierParameter D.rightHairPoint :=
  (I.levelRightHair a).shallowerPoint_parameter_le_left
    D.rightHairPoint (E.adjacentLeftHairPoint hshared)

theorem synchronizedPoint_parameter_le_left
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    (I.levelRightHair a).carrierParameter
        ⟨D.synchronizedPoint E hshared,
          D.synchronizedPoint_mem_levelRightHair E hshared⟩ ≤
      (I.levelRightHair a).carrierParameter
        (E.adjacentLeftHairPoint hshared) :=
  (I.levelRightHair a).shallowerPoint_parameter_le_right
    D.rightHairPoint (E.adjacentLeftHairPoint hshared)

/-- The two possible hair extensions have only their synchronized endpoint
in common.  One extension is necessarily degenerate. -/
theorem synchronized_extensions_inter
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    segment ℝ (D.synchronizedPoint E hshared) D.trimmedRightPoint ∩
        segment ℝ E.trimmedLeftPoint (D.synchronizedPoint E hshared) =
      {D.synchronizedPoint E hshared} := by
  rcases D.synchronizedPoint_eq_right_or_left E hshared with h | h
  · rw [h]
    simp
    exact right_mem_segment ℝ _ _
  · rw [h]
    simp
    exact left_mem_segment ℝ _ _

/-- On the right-hand cell, the synchronized inner extension meets the
boundary-side retained-hair segment only at the synchronized endpoint. -/
theorem right_baseSegment_inter_synchronizedExtension
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    segment ℝ (J.curvePoint (I.levelArc a).right : Plane)
        (D.synchronizedPoint E hshared) ∩
      segment ℝ (D.synchronizedPoint E hshared) D.trimmedRightPoint =
        {D.synchronizedPoint E hshared} := by
  rw [inter_comm]
  exact (I.levelRightHair a).segment_inter_baseSegment_eq
    ⟨D.synchronizedPoint E hshared,
      D.synchronizedPoint_mem_levelRightHair E hshared⟩
    D.rightHairPoint
    (D.synchronizedPoint_parameter_le_right E hshared)

/-- Both synchronization extensions stay strictly inside the original
Jordan circle. -/
theorem right_synchronizedExtension_subset_inside
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    segment ℝ (D.synchronizedPoint E hshared) D.trimmedRightPoint ⊆
      J.inside :=
  (I.levelRightHair a).segment_subset_inside_of_parameter_le
    (J.curvePoint (I.levelArc a).right).2
    ⟨D.synchronizedPoint E hshared,
      D.synchronizedPoint_mem_levelRightHair E hshared⟩
    D.rightHairPoint (D.synchronizedPoint_inside E hshared)
    (D.synchronizedPoint_parameter_le_right E hshared)

theorem left_synchronizedExtension_subset_inside
    (D : I.LevelInsideJoinData a epsilon hepsilon)
    (E : I.LevelInsideJoinData b epsilon hepsilon)
    (hshared :
      (J.curvePoint (I.levelArc a).right : Plane) =
        (J.curvePoint (I.levelArc b).left : Plane)) :
    segment ℝ (D.synchronizedPoint E hshared) E.trimmedLeftPoint ⊆
      J.inside :=
  (I.levelRightHair a).segment_subset_inside_of_parameter_le
    (J.curvePoint (I.levelArc a).right).2
    ⟨D.synchronizedPoint E hshared,
      D.synchronizedPoint_mem_levelRightHair E hshared⟩
    (E.adjacentLeftHairPoint hshared)
    (D.synchronizedPoint_inside E hshared)
    (D.synchronizedPoint_parameter_le_left E hshared)

end LevelInsideJoinData

end InitialAngularArcs
end JordanCircle

end Schoenflies
