/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.LocalizedCutFreeCells
import Submission.Schoenflies.LocalizedJordanAnnularCrosscuts
import Submission.Schoenflies.BoundaryPathTransport

/-!
# Boundary coherence for localized cut-free cells

A localized polygonal shell cell uses a canonical successor pair on its
inner boundary.  The same inner split can be combined with the retained
access-hair prefixes reaching all the way to the original Jordan curve.
Mixed-annulus cyclic order then selects the corresponding cut-free arc of
the original curve.  In particular, the polygonal cell and its eventual
target cell share one boundary labelling rather than making independent
complementary-arc choices.
-/

namespace Schoenflies

open Set Function
open LeanEval.Topology.ClassificationOfSurfaces.Moise

noncomputable section

namespace JordanCircle.InitialAngularArcs

variable {J : JordanCircle} (I : J.InitialAngularArcs)

private abbrev innerDisk (k : ℕ) : PolygonalCircle :=
  I.localizedMarkedPolygonalDisk (k + 1)

namespace LocalizedCutFreeCellData

variable {I : J.InitialAngularArcs} {k : ℕ} {a : LevelAddress k}
  (C : I.LocalizedCutFreeCellData k a)

theorem jordanOuterPoints_ne :
    (I.levelLocalizedJordanAnnularCrosscut k a).outerPoint ≠
      (I.levelLocalizedJordanAnnularCrosscut k C.next).outerPoint := by
  intro h
  exact C.next_ne
    (I.levelLocalizedJordanAnnularCrosscut_outerPoint_injective k h)

/-- The complementary arcs of the original Jordan curve at the two
canonical cell labels. -/
noncomputable def jordanOuterSplit :
    J.TwoBoundaryArcPaths
      (I.levelLocalizedJordanAnnularCrosscut k a).outerPoint
      (I.levelLocalizedJordanAnnularCrosscut k C.next).outerPoint :=
  Classical.choice <| J.exists_twoBoundaryArcPaths
    (I.levelLocalizedJordanAnnularCrosscut k a).outerPoint_mem
    (I.levelLocalizedJordanAnnularCrosscut k C.next).outerPoint_mem
    C.jordanOuterPoints_ne

/-- A mixed separator using exactly the inner split already chosen for the
localized polygonal shell cell. -/
noncomputable def jordanSeparator :
    PolygonalCircle.JordanAnnularCrosscut.SeparatorPair
      (I.levelLocalizedJordanAnnularCrosscut k a)
      (I.levelLocalizedJordanAnnularCrosscut k C.next) where
  innerSplit := C.separator.innerSplit
  outerSplit := C.jordanOuterSplit

@[simp] theorem jordanSeparator_innerSplit :
    C.jordanSeparator.innerSplit = C.separator.innerSplit := rfl

@[simp] theorem jordanSeparator_outerSplit :
    C.jordanSeparator.outerSplit = C.jordanOuterSplit := rfl

private def jordanFirstAlternative : Prop :=
  (I.innerDisk k).interiorRegion ⊆
      (C.jordanSeparator.circle₀
        (I.localizedMarkedPolygonalDisk_closedRegion_subset_inside (k + 1))
        (I.pairwise_disjoint_levelLocalizedJordanAnnularCrosscut k
          C.next_ne)).inside ∧
    ∀ c : LevelAddress k, c ≠ a → c ≠ C.next →
      (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint ∉
        range C.jordanSeparator.outerArc₁

/-- The original Jordan arc corresponding to the exposed side of the
canonical inner split contains no third retained boundary anchor. -/
theorem jordan_cutFreeArcs :
    ((I.innerDisk k).interiorRegion ⊆
          (C.jordanSeparator.circle₀
            (I.localizedMarkedPolygonalDisk_closedRegion_subset_inside
              (k + 1))
            (I.pairwise_disjoint_levelLocalizedJordanAnnularCrosscut k
              C.next_ne)).inside ∧
        ∀ c : LevelAddress k, c ≠ a → c ≠ C.next →
          (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint ∉
            range C.jordanSeparator.outerArc₁) ∨
      ((I.innerDisk k).interiorRegion ⊆
          (C.jordanSeparator.circle₁
            (I.localizedMarkedPolygonalDisk_closedRegion_subset_inside
              (k + 1))
            (I.pairwise_disjoint_levelLocalizedJordanAnnularCrosscut k
              C.next_ne)).inside ∧
        ∀ c : LevelAddress k, c ≠ a → c ≠ C.next →
          (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint ∉
            range C.jordanSeparator.outerArc₀) := by
  exact C.jordanSeparator.family_cutFreeArcs
    (I.levelLocalizedJordanAnnularCrosscut k)
    C.next_ne
    (I.localizedMarkedPolygonalDisk_closedRegion_subset_inside (k + 1))
    (I.pairwise_disjoint_levelLocalizedJordanAnnularCrosscut k)
    (I.levelLocalizedJordanAnnularCrosscut_innerPoint_injective k)
    (I.levelLocalizedJordanAnnularCrosscut_outerPoint_injective k)
    (I.range_levelLocalizedJordanAnnularCrosscut_eq_segment k a)
    (I.range_levelLocalizedJordanAnnularCrosscut_eq_segment k C.next)
    C.inner_second

private theorem jordanSecondAlternative_of_not_first
    (h : ¬ C.jordanFirstAlternative) :
    (I.innerDisk k).interiorRegion ⊆
        (C.jordanSeparator.circle₁
          (I.localizedMarkedPolygonalDisk_closedRegion_subset_inside (k + 1))
          (I.pairwise_disjoint_levelLocalizedJordanAnnularCrosscut k
            C.next_ne)).inside ∧
      ∀ c : LevelAddress k, c ≠ a → c ≠ C.next →
        (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint ∉
          range C.jordanSeparator.outerArc₀ :=
  C.jordan_cutFreeArcs.resolve_left h

/-- The endpoint-free original Jordan arc associated to this localized
cell, oriented from the successor label back to the starting label. -/
noncomputable def jordanExposedOuterArc :
    Path
      (I.levelLocalizedJordanAnnularCrosscut k C.next).outerPoint
      (I.levelLocalizedJordanAnnularCrosscut k a).outerPoint := by
  classical
  exact if C.jordanFirstAlternative then
      C.jordanSeparator.outerArc₁
    else C.jordanSeparator.outerArc₀

theorem jordanExposedOuterArc_injective :
    Injective C.jordanExposedOuterArc := by
  classical
  by_cases h : C.jordanFirstAlternative
  · rw [jordanExposedOuterArc, if_pos h]
    exact C.jordanSeparator.outerSplit.first_injective.comp
      unitInterval.symm_bijective.injective
  · rw [jordanExposedOuterArc, if_neg h]
    exact C.jordanSeparator.outerSplit.second_injective

theorem jordanExposedOuterArc_range_subset :
    range C.jordanExposedOuterArc ⊆ J.carrier := by
  classical
  by_cases h : C.jordanFirstAlternative
  · rw [jordanExposedOuterArc, if_pos h]
    exact C.jordanSeparator.outerArc₁_range_subset
  · rw [jordanExposedOuterArc, if_neg h]
    exact C.jordanSeparator.outerArc₀_range_subset

theorem other_jordanOuterPoint_not_mem_exposedOuterArc :
    ∀ c : LevelAddress k, c ≠ a → c ≠ C.next →
      (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint ∉
        range C.jordanExposedOuterArc := by
  classical
  intro c hca hcnext
  by_cases h : C.jordanFirstAlternative
  · rw [jordanExposedOuterArc, if_pos h]
    exact h.2 c hca hcnext
  · rw [jordanExposedOuterArc, if_neg h]
    exact (C.jordanSecondAlternative_of_not_first h).2 c hca hcnext

/-- Reorient the original complementary split so that its first path runs
along the selected cell from label `a` to label `next`. -/
noncomputable def jordanCellBoundarySplit :
    J.TwoBoundaryArcPaths
      (I.levelLocalizedJordanAnnularCrosscut k a).outerPoint
      (I.levelLocalizedJordanAnnularCrosscut k C.next).outerPoint := by
  classical
  exact if C.jordanFirstAlternative then
      C.jordanOuterSplit
    else C.jordanOuterSplit.swap

theorem jordanCellBoundarySplit_first :
    C.jordanCellBoundarySplit.first = C.jordanExposedOuterArc.symm := by
  classical
  by_cases h : C.jordanFirstAlternative
  · rw [jordanCellBoundarySplit, if_pos h,
      jordanExposedOuterArc, if_pos h]
    simp [PolygonalCircle.JordanAnnularCrosscut.SeparatorPair.outerArc₁]
  · rw [jordanCellBoundarySplit, if_neg h,
      jordanExposedOuterArc, if_neg h]
    simp [PolygonalCircle.JordanAnnularCrosscut.SeparatorPair.outerArc₀]

/-- Every other retained Jordan anchor lies on the complementary path of
the cell-oriented split. -/
theorem other_jordanOuterPoint_mem_cellBoundarySplit_second :
    ∀ c : LevelAddress k, c ≠ a → c ≠ C.next →
      (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint ∈
        range C.jordanCellBoundarySplit.second := by
  intro c hca hcnext
  have hcarrier :
      (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint ∈ J.carrier :=
    (I.levelLocalizedJordanAnnularCrosscut k c).outerPoint_mem
  rw [← C.jordanCellBoundarySplit.cover] at hcarrier
  rcases hcarrier with hfirst | hsecond
  · exact False.elim <|
      C.other_jordanOuterPoint_not_mem_exposedOuterArc c hca hcnext <| by
        rw [← Path.symm_range C.jordanExposedOuterArc,
          ← C.jordanCellBoundarySplit_first]
        exact hfirst
  · exact hsecond

end LocalizedCutFreeCellData

end JordanCircle.InitialAngularArcs

end

end Schoenflies
