/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.LocalizedCellCover
import Submission.Schoenflies.FiniteClosedCoverHomeomorph
import Submission.Schoenflies.JordanCarrierInvariance

/-!
# Gluing the localized collar cells

The canonical cell homeomorphisms agree on every source overlap, and their
inverses agree on every target overlap.  The finite closed-cover theorem
therefore glues them to one homeomorphism from the localized polygonal shell
onto the union of the corresponding standard target cells.
-/

namespace Schoenflies

open Set
open LeanEval.Topology.ClassificationOfSurfaces.Moise

noncomputable section

namespace JordanCircle.InitialAngularArcs

variable {J : JordanCircle} (I : J.InitialAngularArcs)

private abbrev innerDisk (k : ℕ) : PolygonalCircle :=
  I.localizedMarkedPolygonalDisk (k + 1)

private abbrev outerDisk (k : ℕ) : PolygonalCircle :=
  I.localizedMarkedPolygonalDisk (k + 2)

private abbrev sourceCell (k : ℕ) (a : LevelAddress k) : Set Plane :=
  (I.localizedCutFreeCellData k a).disk.closedRegion

private abbrev targetCell (k : ℕ) (a : LevelAddress k) : Set Plane :=
  (I.localizedCutFreeCellData k a).targetAttachmentPresentation.disk.closedRegion

theorem finiteCover_sourceCell_eq_iUnion (k : ℕ) :
    FiniteClosedCoverHomeomorph.cover
        (Finset.univ : Finset (LevelAddress k)) (I.sourceCell k) =
      ⋃ a : LevelAddress k, I.sourceCell k a := by
  ext x
  simp only [FiniteClosedCoverHomeomorph.mem_cover_iff,
    Finset.mem_univ, true_and, Set.mem_iUnion]

theorem finiteCover_targetCell_eq_iUnion (k : ℕ) :
    FiniteClosedCoverHomeomorph.cover
        (Finset.univ : Finset (LevelAddress k)) (I.targetCell k) =
      ⋃ a : LevelAddress k, I.targetCell k a := by
  ext x
  simp only [FiniteClosedCoverHomeomorph.mem_cover_iff,
    Finset.mem_univ, true_and, Set.mem_iUnion]

private theorem sourceCell_isClosed (k : ℕ) (a : LevelAddress k) :
    IsClosed (I.sourceCell k a) :=
  (I.localizedCutFreeCellData k a).disk.isCompact_closedRegion.isClosed

private theorem targetCell_isClosed (k : ℕ) (a : LevelAddress k) :
    IsClosed (I.targetCell k a) :=
  (I.localizedCutFreeCellData k a).targetAttachmentPresentation.disk.isCompact_closedRegion.isClosed

/-- The closed-cover gluing before identifying either finite cover with a
geometrically named shell. -/
noncomputable def localizedCellFiniteCoverHomeomorph
    (k : ℕ) (hk : 1 ≤ k) :
    FiniteClosedCoverHomeomorph.cover
        (Finset.univ : Finset (LevelAddress k)) (I.sourceCell k) ≃ₜ
      FiniteClosedCoverHomeomorph.cover
        (Finset.univ : Finset (LevelAddress k)) (I.targetCell k) :=
  FiniteClosedCoverHomeomorph.glue
    Finset.univ (I.sourceCell k) (I.targetCell k)
    (fun a _ => I.sourceCell_isClosed k a)
    (fun a _ => I.targetCell_isClosed k a)
    (fun a => (I.localizedCutFreeCellData k a).cellHomeomorph)
    (fun a _ b _ x hxa hxb =>
      I.canonicalLocalizedCellHomeomorph_agree k hk a b hxa hxb)
    (fun a _ b _ y hya hyb =>
      I.canonicalLocalizedCellHomeomorph_symm_agree k hk a b hya hyb)

/-- The glued cell map, with its domain and codomain written as ordinary
unions rather than finite-cover wrappers. -/
noncomputable def localizedCellUnionHomeomorph
    (k : ℕ) (hk : 1 ≤ k) :
    (⋃ a : LevelAddress k, I.sourceCell k a) ≃ₜ
      (⋃ a : LevelAddress k, I.targetCell k a) :=
  (Homeomorph.setCongr (I.finiteCover_sourceCell_eq_iUnion k).symm).trans <|
    (I.localizedCellFiniteCoverHomeomorph k hk).trans <|
      Homeomorph.setCongr (I.finiteCover_targetCell_eq_iUnion k)

/-- At each member of the source cover, the glued map is the originally
constructed cell homeomorphism. -/
theorem localizedCellUnionHomeomorph_apply
    (k : ℕ) (hk : 1 ≤ k) (a : LevelAddress k) {x : Plane}
    (hx : x ∈ I.sourceCell k a) :
    (I.localizedCellUnionHomeomorph k hk
        ⟨x, Set.mem_iUnion.mpr ⟨a, hx⟩⟩ : Plane) =
      ((I.localizedCutFreeCellData k a).cellHomeomorph ⟨x, hx⟩ : Plane) := by
  change
    (I.localizedCellFiniteCoverHomeomorph k hk
      ⟨x, FiniteClosedCoverHomeomorph.subset_cover
        (Finset.mem_univ a) hx⟩ : Plane) = _
  exact FiniteClosedCoverHomeomorph.coe_glue_apply
    Finset.univ (I.sourceCell k) (I.targetCell k)
    (fun a _ => I.sourceCell_isClosed k a)
    (fun a _ => I.targetCell_isClosed k a)
    (fun a => (I.localizedCutFreeCellData k a).cellHomeomorph)
    (fun a _ b _ x hxa hxb =>
      I.canonicalLocalizedCellHomeomorph_agree k hk a b hxa hxb)
    (fun a _ b _ y hya hyb =>
      I.canonicalLocalizedCellHomeomorph_symm_agree k hk a b hya hyb)
    a (Finset.mem_univ a) x hx

/-- The finite-stage homeomorphism from the actual localized source shell
onto the union of standard target cells. -/
noncomputable def localizedShellToTargetCellUnionHomeomorph
    (k : ℕ) (hk : 1 ≤ k) :
    PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) ≃ₜ
      (⋃ a : LevelAddress k, I.targetCell k a) :=
  (Homeomorph.setCongr
      (I.iUnion_localizedCell_closedRegion_eq_closedShell k hk).symm).trans
    (I.localizedCellUnionHomeomorph k hk)

theorem localizedShellToTargetCellUnionHomeomorph_apply
    (k : ℕ) (hk : 1 ≤ k) (a : LevelAddress k) {x : Plane}
    (hxShell : x ∈
      PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k))
    (hxCell : x ∈ I.sourceCell k a) :
    (I.localizedShellToTargetCellUnionHomeomorph k hk
        ⟨x, hxShell⟩ : Plane) =
      ((I.localizedCutFreeCellData k a).cellHomeomorph
        ⟨x, hxCell⟩ : Plane) := by
  change
    (I.localizedCellUnionHomeomorph k hk
      ⟨x, Set.mem_iUnion.mpr ⟨a, hxCell⟩⟩ : Plane) = _
  exact I.localizedCellUnionHomeomorph_apply k hk a hxCell

/-- Restrict the finite-stage glued map to the source shell's outer boundary. -/
noncomputable def localizedOuterBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    (I.outerDisk k).toJordanCircle.carrier → Plane := fun x =>
  let hxOuter : (x : Plane) ∈ (I.outerDisk k).carrier := by
    simpa only [(I.outerDisk k).carrier_toJordanCircle] using x.2
  let hxShell : (x : Plane) ∈
      PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    PolygonalCircle.outerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) hxOuter
  (I.localizedShellToTargetCellUnionHomeomorph k hk
    ⟨x, hxShell⟩ : Plane)

theorem continuous_localizedOuterBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    Continuous (I.localizedOuterBoundaryEmbedding k hk) := by
  let inclusion : (I.outerDisk k).toJordanCircle.carrier →
      PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) := fun x =>
    ⟨x, PolygonalCircle.outerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) <| by
        simpa only [(I.outerDisk k).carrier_toJordanCircle] using x.2⟩
  have hinclusion : Continuous inclusion :=
    continuous_subtype_val.subtype_mk _
  exact continuous_subtype_val.comp <|
    (I.localizedShellToTargetCellUnionHomeomorph k hk).continuous.comp
      hinclusion

theorem injective_localizedOuterBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    Function.Injective (I.localizedOuterBoundaryEmbedding k hk) := by
  intro x y hxy
  let sx : PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    ⟨x, PolygonalCircle.outerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) <| by
        simpa only [(I.outerDisk k).carrier_toJordanCircle] using x.2⟩
  let sy : PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    ⟨y, PolygonalCircle.outerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) <| by
        simpa only [(I.outerDisk k).carrier_toJordanCircle] using y.2⟩
  have hmap : I.localizedShellToTargetCellUnionHomeomorph k hk sx =
      I.localizedShellToTargetCellUnionHomeomorph k hk sy := by
    apply Subtype.ext
    exact hxy
  have hs :=
    (I.localizedShellToTargetCellUnionHomeomorph k hk).injective hmap
  have hval : (sx : Plane) = (sy : Plane) :=
    congrArg (fun z : PolygonalCircle.closedShell
      (I.innerDisk k) (I.outerDisk k) => (z : Plane)) hs
  exact Subtype.ext hval

theorem localizedOuterBoundaryEmbedding_mem_targetOuterCarrier
    (k : ℕ) (hk : 1 ≤ k)
    (x : (I.outerDisk k).toJordanCircle.carrier) :
    I.localizedOuterBoundaryEmbedding k hk x ∈
      (StandardPolygonalCollars.disk (k + 2)).carrier := by
  have hxOuter : (x : Plane) ∈ (I.outerDisk k).carrier := by
    simpa only [(I.outerDisk k).carrier_toJordanCircle] using x.2
  have hxShell : (x : Plane) ∈
      PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    PolygonalCircle.outerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) hxOuter
  have hxCells : (x : Plane) ∈
      ⋃ a : LevelAddress k, I.sourceCell k a := by
    rw [I.iUnion_localizedCell_closedRegion_eq_closedShell k hk]
    exact hxShell
  obtain ⟨a, hxCell⟩ := Set.mem_iUnion.mp hxCells
  rw [localizedOuterBoundaryEmbedding]
  rw [I.localizedShellToTargetCellUnionHomeomorph_apply
    k hk a hxShell hxCell]
  exact (I.localizedCutFreeCellData k a).cellHomeomorph_mem_targetOuterCarrier_of_mem_outerCarrier
      hk hxCell hxOuter

/-- The glued outer-boundary embedding is onto the entire standard target
boundary. -/
theorem range_localizedOuterBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    Set.range (I.localizedOuterBoundaryEmbedding k hk) =
      (StandardPolygonalCollars.disk (k + 2)).carrier := by
  simpa only
      [(StandardPolygonalCollars.disk (k + 2)).carrier_toJordanCircle] using
    (I.outerDisk k).toJordanCircle.range_eq_carrier_of_continuous_injective
      (StandardPolygonalCollars.disk (k + 2)).toJordanCircle
      (I.localizedOuterBoundaryEmbedding k hk)
      (I.continuous_localizedOuterBoundaryEmbedding k hk)
      (I.injective_localizedOuterBoundaryEmbedding k hk)
      (fun x => by
        simpa only
          [(StandardPolygonalCollars.disk (k + 2)).carrier_toJordanCircle] using
            I.localizedOuterBoundaryEmbedding_mem_targetOuterCarrier k hk x)

/-- Restrict the finite-stage glued map to the source shell's inner boundary. -/
noncomputable def localizedInnerBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    (I.innerDisk k).toJordanCircle.carrier → Plane := fun x =>
  let hxInner : (x : Plane) ∈ (I.innerDisk k).carrier := by
    simpa only [(I.innerDisk k).carrier_toJordanCircle] using x.2
  let hxShell : (x : Plane) ∈
      PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    PolygonalCircle.innerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) hxInner
  (I.localizedShellToTargetCellUnionHomeomorph k hk
    ⟨x, hxShell⟩ : Plane)

theorem continuous_localizedInnerBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    Continuous (I.localizedInnerBoundaryEmbedding k hk) := by
  let inclusion : (I.innerDisk k).toJordanCircle.carrier →
      PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) := fun x =>
    ⟨x, PolygonalCircle.innerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) <| by
        simpa only [(I.innerDisk k).carrier_toJordanCircle] using x.2⟩
  have hinclusion : Continuous inclusion :=
    continuous_subtype_val.subtype_mk _
  exact continuous_subtype_val.comp <|
    (I.localizedShellToTargetCellUnionHomeomorph k hk).continuous.comp
      hinclusion

theorem injective_localizedInnerBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    Function.Injective (I.localizedInnerBoundaryEmbedding k hk) := by
  intro x y hxy
  let sx : PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    ⟨x, PolygonalCircle.innerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) <| by
        simpa only [(I.innerDisk k).carrier_toJordanCircle] using x.2⟩
  let sy : PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    ⟨y, PolygonalCircle.innerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) <| by
        simpa only [(I.innerDisk k).carrier_toJordanCircle] using y.2⟩
  have hmap : I.localizedShellToTargetCellUnionHomeomorph k hk sx =
      I.localizedShellToTargetCellUnionHomeomorph k hk sy := by
    apply Subtype.ext
    exact hxy
  have hs :=
    (I.localizedShellToTargetCellUnionHomeomorph k hk).injective hmap
  have hval : (sx : Plane) = (sy : Plane) :=
    congrArg (fun z : PolygonalCircle.closedShell
      (I.innerDisk k) (I.outerDisk k) => (z : Plane)) hs
  exact Subtype.ext hval

theorem localizedInnerBoundaryEmbedding_mem_targetInnerCarrier
    (k : ℕ) (hk : 1 ≤ k)
    (x : (I.innerDisk k).toJordanCircle.carrier) :
    I.localizedInnerBoundaryEmbedding k hk x ∈
      (StandardPolygonalCollars.disk (k + 1)).carrier := by
  have hxInner : (x : Plane) ∈ (I.innerDisk k).carrier := by
    simpa only [(I.innerDisk k).carrier_toJordanCircle] using x.2
  have hxShell : (x : Plane) ∈
      PolygonalCircle.closedShell (I.innerDisk k) (I.outerDisk k) :=
    PolygonalCircle.innerCarrier_subset_closedShell
      (I.innerDisk k) (I.outerDisk k)
      (I.localizedMarkedPolygonalDisk_strictly_nested (k + 1)) hxInner
  obtain ⟨a, hxShared⟩ := Set.mem_iUnion.mp <|
    I.innerCarrier_subset_iUnion_localizedCellShared k hk hxInner
  obtain ⟨t, ht⟩ := hxShared
  have hxCell : (x : Plane) ∈ I.sourceCell k a := by
    rw [← ht]
    exact (I.localizedCutFreeCellData k a).attachmentPresentation.shared_mem_closedRegion t
  rw [localizedInnerBoundaryEmbedding]
  rw [I.localizedShellToTargetCellUnionHomeomorph_apply
    k hk a hxShell hxCell]
  rw [show
    ((I.localizedCutFreeCellData k a).cellHomeomorph
      ⟨(x : Plane), hxCell⟩ : Plane) =
        (I.localizedCutFreeCellData k a).targetAttachmentPresentation.shared t by
      calc
        ((I.localizedCutFreeCellData k a).cellHomeomorph
            ⟨(x : Plane), hxCell⟩ : Plane) =
            ((I.localizedCutFreeCellData k a).cellHomeomorph
              ⟨(I.localizedCutFreeCellData k a).attachmentPresentation.shared t,
                (I.localizedCutFreeCellData k a).attachmentPresentation.shared_mem_closedRegion t⟩ :
                  Plane) := by
            apply congrArg (fun z =>
              ((I.localizedCutFreeCellData k a).cellHomeomorph z : Plane))
            exact Subtype.ext ht.symm
        _ = (I.localizedCutFreeCellData k a).targetAttachmentPresentation.shared t :=
          (I.localizedCutFreeCellData k a).cellHomeomorph_apply_shared t]
  apply (I.localizedCutFreeCellData k a).targetSeparator.innerFirst_range_subset
  change (I.localizedCutFreeCellData k a).targetAttachmentPresentation.shared t ∈
    range ((I.localizedCutFreeCellData k a).targetBoundarySplit (k + 1)).first
  rw [← (I.localizedCutFreeCellData k a).range_targetAttachmentPresentation_shared]
  exact ⟨t, rfl⟩

/-- The glued inner-boundary embedding is onto the entire standard target
boundary. -/
theorem range_localizedInnerBoundaryEmbedding
    (k : ℕ) (hk : 1 ≤ k) :
    Set.range (I.localizedInnerBoundaryEmbedding k hk) =
      (StandardPolygonalCollars.disk (k + 1)).carrier := by
  simpa only
      [(StandardPolygonalCollars.disk (k + 1)).carrier_toJordanCircle] using
    (I.innerDisk k).toJordanCircle.range_eq_carrier_of_continuous_injective
      (StandardPolygonalCollars.disk (k + 1)).toJordanCircle
      (I.localizedInnerBoundaryEmbedding k hk)
      (I.continuous_localizedInnerBoundaryEmbedding k hk)
      (I.injective_localizedInnerBoundaryEmbedding k hk)
      (fun x => by
        simpa only
          [(StandardPolygonalCollars.disk (k + 1)).carrier_toJordanCircle] using
            I.localizedInnerBoundaryEmbedding_mem_targetInnerCarrier k hk x)

/-- The target-cell union lies in the expected standard polygonal shell. -/
theorem iUnion_targetCell_subset_standardClosedShell
    (k : ℕ) (hk : 1 ≤ k) :
    (⋃ a : LevelAddress k, I.targetCell k a) ⊆
      PolygonalCircle.closedShell
        (StandardPolygonalCollars.disk (k + 1))
        (StandardPolygonalCollars.disk (k + 2)) := by
  apply Set.iUnion_subset
  intro a x hxCell
  let C : I.LocalizedCutFreeCellData k a :=
    I.localizedCutFreeCellData k a
  refine ⟨C.targetDisk_closedRegion_subset_outerDisk hk hxCell, ?_⟩
  intro hxInnerInterior
  have hxInnerClosed : x ∈
      (StandardPolygonalCollars.disk (k + 1)).closedRegion := by
    rw [(StandardPolygonalCollars.disk (k + 1)).closedRegion_eq_union]
    exact Or.inl hxInnerInterior
  have hxShared : x ∈ range C.targetAttachmentPresentation.shared := by
    rw [← C.targetAttachmentPresentation.base_inter_disk]
    exact ⟨hxInnerClosed, hxCell⟩
  have hxInnerCarrier : x ∈
      (StandardPolygonalCollars.disk (k + 1)).carrier := by
    rw [C.range_targetAttachmentPresentation_shared] at hxShared
    exact C.targetSeparator.innerFirst_range_subset hxShared
  exact Set.disjoint_left.mp
    (PolygonalCircle.carrier_disjoint_interiorRegion
      (StandardPolygonalCollars.disk (k + 1)))
    hxInnerCarrier hxInnerInterior

end JordanCircle.InitialAngularArcs

end

end Schoenflies
