/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.PolygonalTransport
import Submission.ClassificationOfSurfaces.Moise.Anchors
import Submission.ClassificationOfSurfaces.Moise.ConeExtension
import Submission.ClassificationOfSurfaces.Moise.PolygonalSchoenflies
import Mathlib.Analysis.Convex.GaugeRescale

/-!
# Polygonal circles as parametrized Jordan circles

The Moise development represents a polygon by its cyclic straight edges,
whereas the vendored Jordan theorem accepts an injective parametrization of
the Euclidean unit circle.  Polygonal Schoenflies and gauge rescaling give a
small, reusable bridge between those interfaces.
-/

open Metric Set Function Bornology

namespace LeanEval.Topology.ClassificationOfSurfaces.Moise

open Schoenflies

namespace PolygonalCircle

/-- Every polygonal circle admits an ambient straightening to the Euclidean
unit circle. -/
theorem exists_sphereStraightening (P : PolygonalCircle) :
    ∃ h : Plane ≃ₜ Plane, h '' P.carrier = sphere (0 : Plane) 1 := by
  let C : Set Plane := convexHull ℝ (Set.range standardTriangleVertex)
  have hC : IsTriangle C :=
    ⟨standardTriangleVertex, standardTriangleVertex_affineIndependent, rfl⟩
  obtain ⟨e, _hInterior, _hClosure, hFrontier⟩ :=
    exists_homeomorph_image_interior_closure_frontier_eq_unitBall
      hC.convex hC.infinite_interior.nonempty hC.isCompact.isBounded
  obtain ⟨g, hg⟩ := P.polygonal_schoenflies standardTriangleCircle
  refine ⟨g.trans e, ?_⟩
  have himage : e '' (g '' P.carrier) = sphere (0 : Plane) 1 := by
    rw [hg, standardTriangleCircle_carrier]
    exact hFrontier
  rw [image_image] at himage
  simpa using himage

/-- A fixed ambient straightening of a polygonal circle. -/
noncomputable def sphereStraightening (P : PolygonalCircle) : Plane ≃ₜ Plane :=
  Classical.choose P.exists_sphereStraightening

theorem sphereStraightening_image_carrier (P : PolygonalCircle) :
    P.sphereStraightening '' P.carrier = sphere (0 : Plane) 1 :=
  Classical.choose_spec P.exists_sphereStraightening

/-- Regard a polygonal circle as a parametrized Jordan circle, without
changing its point-set carrier. -/
noncomputable def toJordanCircle (P : PolygonalCircle) : JordanCircle where
  parametrization := fun x => P.sphereStraightening.symm x
  continuous :=
    P.sphereStraightening.symm.continuous.comp continuous_subtype_val
  injective := by
    intro x y hxy
    exact Subtype.ext (P.sphereStraightening.symm.injective hxy)

@[simp] theorem carrier_toJordanCircle (P : PolygonalCircle) :
    P.toJordanCircle.carrier = P.carrier := by
  ext x
  constructor
  · rintro ⟨u, rfl⟩
    change P.sphereStraightening.symm (u : Plane) ∈ P.carrier
    have huImage : (u : Plane) ∈
        P.sphereStraightening '' P.carrier := by
      rw [P.sphereStraightening_image_carrier]
      exact u.2
    obtain ⟨y, hy, hyu⟩ := huImage
    have hyEq : y = P.sphereStraightening.symm u := by
      apply P.sphereStraightening.injective
      rw [P.sphereStraightening.apply_symm_apply]
      exact hyu
    rwa [← hyEq]
  · intro hx
    let u : sphere (0 : Plane) 1 :=
      ⟨P.sphereStraightening x, by
        rw [← P.sphereStraightening_image_carrier]
        exact ⟨x, hx, rfl⟩⟩
    refine ⟨u, ?_⟩
    exact P.sphereStraightening.symm_apply_apply x

/-- The Jordan-theorem bounded side agrees with the polygonal bounded
region already constructed in the Moise development. -/
theorem inside_toJordanCircle (P : PolygonalCircle) :
    P.toJordanCircle.inside = P.interiorRegion := by
  let K := P.toJordanCircle
  have hpointCompl : K.insidePoint ∈ P.carrierᶜ := by
    rw [← P.carrier_toJordanCircle]
    exact K.insidePoint_mem
  have hcomponent :
      connectedComponentIn P.carrierᶜ K.insidePoint = K.inside := by
    rw [JordanCircle.inside, P.carrier_toJordanCircle]
  have hpointRegions :
      K.insidePoint ∈ P.interiorRegion ∪ P.exteriorRegion := by
    rwa [P.interior_union_exterior]
  rcases hpointRegions with hpointInside | hpointOutside
  · rw [← hcomponent]
    exact PolygonalTransport.connectedComponentIn_eq_interiorRegion
      P hpointInside
  · have hOutsideComponent :=
      PolygonalTransport.connectedComponentIn_eq_exteriorRegion
        P hpointOutside
    exact False.elim <| P.not_isBounded_exteriorRegion <| by
      rw [← hOutsideComponent, hcomponent]
      exact K.inside_bounded

/-- The unbounded regions agree as well. -/
theorem outside_toJordanCircle (P : PolygonalCircle) :
    P.toJordanCircle.outside = P.exteriorRegion := by
  let K := P.toJordanCircle
  apply Set.Subset.antisymm
  · intro x hxOutside
    have hxCompl : x ∈ P.carrierᶜ := by
      rw [← P.carrier_toJordanCircle]
      exact K.outside_subset_compl hxOutside
    have hxRegions : x ∈ P.interiorRegion ∪ P.exteriorRegion := by
      rwa [P.interior_union_exterior]
    rcases hxRegions with hxInside | hxExterior
    · have hxKInside : x ∈ K.inside := by
        rw [P.inside_toJordanCircle]
        exact hxInside
      exact False.elim
        (Set.disjoint_left.mp K.inside_disjoint_outside hxKInside hxOutside)
    · exact hxExterior
  · intro x hxExterior
    have hxCompl : x ∈ K.carrierᶜ := by
      rw [P.carrier_toJordanCircle]
      rw [← P.interior_union_exterior]
      exact Or.inr hxExterior
    rcases K.mem_inside_or_outside hxCompl with hxInside | hxOutside
    · have hxPInside : x ∈ P.interiorRegion := by
        rw [← P.inside_toJordanCircle]
        exact hxInside
      exact False.elim
        (Set.disjoint_left.mp P.disjoint_interior_exterior hxPInside hxExterior)
    · exact hxOutside

end PolygonalCircle

end LeanEval.Topology.ClassificationOfSurfaces.Moise
