/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.PolygonalBoundaryArcComparison
import Submission.Schoenflies.PolygonalPaths
import Submission.Schoenflies.SegmentChainWalk

/-!
# Polygonal cycles from two finite embedded arcs

This file bridges the point-set Jordan separators used in Chapter 9 to the
finite `PolygonalCircle` interface used by the polygonal disk-extension
theorem.  The first step records a useful rigidity fact: a connected subset
of an embedded interval which contains both endpoints is the whole interval.
-/

namespace Schoenflies

open Set Function
open LeanEval.Topology.ClassificationOfSurfaces.Moise

noncomputable section

namespace Path

/-- A preconnected subset of an injective path range which contains both
endpoints is the entire path range. -/
theorem eq_range_of_isPreconnected_subset
    {x y : Plane} (p : Path x y) (hp : Injective p)
    {C : Set Plane} (hC : IsPreconnected C)
    (hsub : C ⊆ range p) (hx : x ∈ C) (hy : y ∈ C) :
    C = range p := by
  have hpClosed : IsClosedMap p := p.continuous.isClosedMap
  have hpreimage : IsPreconnected (p ⁻¹' C) :=
    hC.preimage_of_isClosedMap hp hpClosed hsub
  have hord : OrdConnected (p ⁻¹' C) :=
    isPreconnected_iff_ordConnected.mp hpreimage
  apply Set.Subset.antisymm hsub
  rintro z ⟨t, rfl⟩
  have hzero : (0 : unitInterval) ∈ p ⁻¹' C := by
    simpa only [Set.mem_preimage, p.source] using hx
  have hone : (1 : unitInterval) ∈ p ⁻¹' C := by
    simpa only [Set.mem_preimage, p.target] using hy
  exact hord.out hzero hone ⟨bot_le, le_top⟩

end Path

namespace JordanCircle.SimpleBrokenLine

variable {x y : Plane}

/-- Loop erasure inside an already embedded path cannot shorten the carrier:
the resolved path is connected and still contains both endpoints. -/
theorem range_toPath_eq_of_subset_injectivePath
    {U : Set Plane} (B : SimpleBrokenLine U x y) (hxy : x ≠ y)
    (p : Path x y) (hp : Injective p) (hU : U ⊆ range p) :
    range (B.toPath hxy) = range p := by
  exact Schoenflies.Path.eq_range_of_isPreconnected_subset p hp
    (isPreconnected_range (B.toPath hxy).continuous)
    ((B.range_toPath_subset hxy).trans hU)
    (Path.source_mem_range (B.toPath hxy))
    (Path.target_mem_range (B.toPath hxy))

/-- A finite broken-line join lying in an injective path produces a resolved
simple broken line with exactly the same point-set carrier as that path. -/
theorem range_simpleBrokenLineOfJoined_eq
    (p : Path x y) (hp : Injective p) (hxy : x ≠ y)
    (hjoin : JoinedByBrokenLine (range p) x y) :
    range ((JordanCircle.simpleBrokenLineOfJoined hjoin).toPath hxy) =
      range p := by
  exact range_toPath_eq_of_subset_injectivePath
    (JordanCircle.simpleBrokenLineOfJoined hjoin) hxy p hp Subset.rfl

/-- Distinct endpoints force the resolved graph path to have an edge. -/
theorem resolvedWalk_length_pos
    {U : Set Plane} (B : SimpleBrokenLine U x y) (hxy : x ≠ y) :
    0 < B.data.resolvedWalk.length := by
  let D := B.carrierBrokenLine hxy
  have hstartFinish : D.data.start ≠ D.data.finish := by
    intro h
    apply hxy
    exact D.start_eq.symm.trans (h.trans D.finish_eq)
  exact JordanCircle.BrokenLineData.n_pos_of_start_ne_finish
    D.data hstartFinish

end JordanCircle.SimpleBrokenLine

namespace BrokenLineData

private abbrev MoiseBrokenLineData :=
  LeanEval.Topology.ClassificationOfSurfaces.Moise.BrokenLineData

/-- Ordered edges of a loop-resolved broken line meet only at their common
successive endpoint. -/
theorem resolvedSegment_inter_subset_right
    {U : Set Plane} (B : MoiseBrokenLineData U)
    (i j : Fin B.resolvedWalk.length) (hij : i < j) :
    segment ℝ (B.resolvedVertex i.castSucc) (B.resolvedVertex i.succ) ∩
        segment ℝ (B.resolvedVertex j.castSucc) (B.resolvedVertex j.succ) ⊆
      {B.resolvedVertex i.succ} := by
  let K := B.arrangementMesh.toPlaneComplex
  let ei : Finset K.Vertex :=
    {B.resolvedWalk.getVert i.val, B.resolvedWalk.getVert (i.val + 1)}
  let ej : Finset K.Vertex :=
    {B.resolvedWalk.getVert j.val, B.resolvedWalk.getVert (j.val + 1)}
  have hinterVertices : ∀ v : K.Vertex, v ∈ ei → v ∈ ej →
      v = B.resolvedWalk.getVert (i.val + 1) := by
    intro v hvei hvej
    have hvi : v = B.resolvedWalk.getVert i.val ∨
        v = B.resolvedWalk.getVert (i.val + 1) := by
      dsimp only [ei] at hvei
      simpa only [Finset.mem_insert, Finset.mem_singleton] using hvei
    have hvj : v = B.resolvedWalk.getVert j.val ∨
        v = B.resolvedWalk.getVert (j.val + 1) := by
      dsimp only [ej] at hvej
      simpa only [Finset.mem_insert, Finset.mem_singleton] using hvej
    rcases hvi with hvi | hvi
    · rcases hvj with hvj | hvj
      · have heq : i.val = j.val := by
          exact B.resolvedPath.property.getVert_injOn
            (Nat.le_of_lt i.isLt) (Nat.le_of_lt j.isLt)
            (hvi.symm.trans hvj)
        omega
      · have heq : i.val = j.val + 1 := by
          exact B.resolvedPath.property.getVert_injOn
            (Nat.le_of_lt i.isLt) j.isLt (hvi.symm.trans hvj)
        omega
    · exact hvi
  intro z hz
  rw [B.resolvedSegment_inter i j] at hz
  change z ∈ convexHull ℝ (K.position '' ((ei ∩ ej : Finset K.Vertex) :
    Set K.Vertex)) at hz
  have himage : K.position '' ((ei ∩ ej : Finset K.Vertex) : Set K.Vertex) ⊆
      {B.resolvedVertex i.succ} := by
    rintro q ⟨v, hv, rfl⟩
    have hvMem := Finset.mem_inter.mp hv
    have hv' := hinterVertices v hvMem.1 hvMem.2
    rw [Set.mem_singleton_iff]
    change K.position v = K.position (B.resolvedWalk.getVert (i.val + 1))
    rw [hv']
  have hz' := convexHull_mono himage hz
  simpa only [convexHull_singleton, Set.mem_singleton_iff] using hz'

end BrokenLineData

namespace PlaneComplex

/-- Reversing a finite graph walk does not change its geometric carrier. -/
theorem range_walkGeometricPath_reverse
    (K : PlaneComplex) {u v : K.Vertex}
    (p : K.vertexGraph.Walk u v) :
    range (K.walkGeometricPath p.reverse) =
      range (K.walkGeometricPath p) := by
  by_cases hp : p.Nil
  · cases hp
    simp
  apply Set.Subset.antisymm
  · apply BrokenLineData.range_walkGeometricPath_mono_edges_of_not_nil
      K p.reverse p
    · simpa using hp
    · intro e he
      simpa using he
  · apply BrokenLineData.range_walkGeometricPath_mono_edges_of_not_nil
      K p p.reverse hp
    intro e he
    simpa using he

end PlaneComplex

namespace TwoArcSegmentFamily

open JordanCircle

variable {U V : Set Plane} {x y : Plane}

/-- Labels for every resolved segment in two polygonal arcs. -/
abbrev Address (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) :=
  Fin B.data.resolvedWalk.length ⊕ Fin C.data.resolvedWalk.length

def left (B : SimpleBrokenLine U x y) (C : SimpleBrokenLine V y x) :
    Address B C → Plane
  | Sum.inl i => B.data.resolvedVertex i.castSucc
  | Sum.inr i => C.data.resolvedVertex i.castSucc

def right (B : SimpleBrokenLine U x y) (C : SimpleBrokenLine V y x) :
    Address B C → Plane
  | Sum.inl i => B.data.resolvedVertex i.succ
  | Sum.inr i => C.data.resolvedVertex i.succ

def firstSegments (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) : List (Address B C) :=
  List.ofFn fun i => Sum.inl i

def secondSegments (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) : List (Address B C) :=
  List.ofFn fun i => Sum.inr i

theorem firstSegments_nonempty (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) (hxy : x ≠ y) :
    firstSegments B C ≠ [] := by
  intro hnil
  have hzero : B.data.resolvedWalk.length = 0 := by
    exact List.ofFn_eq_nil_iff.mp hnil
  exact (B.resolvedWalk_length_pos hxy).ne' hzero

theorem secondSegments_nonempty (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) (hxy : x ≠ y) :
    secondSegments B C ≠ [] := by
  intro hnil
  have hzero : C.data.resolvedWalk.length = 0 := by
    exact List.ofFn_eq_nil_iff.mp hnil
  exact (C.resolvedWalk_length_pos hxy.symm).ne' hzero

theorem firstSegments_isChain (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) :
    (firstSegments B C).IsChain fun i j => right B C i = left B C j := by
  rw [firstSegments, List.isChain_ofFn]
  intro i hi
  simp only [right, left]
  congr 1

theorem secondSegments_isChain (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) :
    (secondSegments B C).IsChain fun i j => right B C i = left B C j := by
  rw [secondSegments, List.isChain_ofFn]
  intro i hi
  simp only [right, left]
  congr 1

theorem firstSegments_pairwise (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) :
    (firstSegments B C).Pairwise fun i j =>
      segment ℝ (left B C i) (right B C i) ∩
          segment ℝ (left B C j) (right B C j) ⊆
        {right B C i} := by
  rw [firstSegments, List.pairwise_ofFn]
  intro i j hij
  exact Schoenflies.BrokenLineData.resolvedSegment_inter_subset_right
    B.data i j hij

theorem secondSegments_pairwise (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) :
    (secondSegments B C).Pairwise fun i j =>
      segment ℝ (left B C i) (right B C i) ∩
          segment ℝ (left B C j) (right B C j) ⊆
        {right B C i} := by
  rw [secondSegments, List.pairwise_ofFn]
  intro i j hij
  exact Schoenflies.BrokenLineData.resolvedSegment_inter_subset_right
    C.data i j hij

theorem firstSegments_ne (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) :
    ∀ i ∈ firstSegments B C, left B C i ≠ right B C i := by
  intro i hi
  obtain ⟨j, hj⟩ : ∃ j, Sum.inl j = i := by
    simpa only [firstSegments, List.mem_ofFn] using hi
  subst i
  intro h
  have hfin : j.castSucc = j.succ :=
    B.data.resolvedVertex_injective h
  have hval := congrArg Fin.val hfin
  simp only [Fin.val_castSucc, Fin.val_succ] at hval
  omega

theorem secondSegments_ne (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) :
    ∀ i ∈ secondSegments B C, left B C i ≠ right B C i := by
  intro i hi
  obtain ⟨j, hj⟩ : ∃ j, Sum.inr j = i := by
    simpa only [secondSegments, List.mem_ofFn] using hi
  subst i
  intro h
  have hfin : j.castSucc = j.succ :=
    C.data.resolvedVertex_injective h
  have hval := congrArg Fin.val hfin
  simp only [Fin.val_castSucc, Fin.val_succ] at hval
  omega

noncomputable abbrev complex (B : SimpleBrokenLine U x y)
    (C : SimpleBrokenLine V y x) : PlaneComplex :=
  BrokenLineData.segmentFamilyComplex (left B C) (right B C)

/-- The first resolved arc becomes a simple graph path in the common
arrangement of both arcs, with its exact original resolved carrier. -/
theorem exists_firstPath
    (B : SimpleBrokenLine U x y) (C : SimpleBrokenLine V y x)
    (hxy : x ≠ y) :
    ∃ u v : (complex B C).Vertex,
      ∃ p : (complex B C).vertexGraph.Path u v,
        range ((complex B C).walkGeometricPath p.1) =
            B.data.resolvedCarrier ∧
          (complex B C).position u = x ∧
          (complex B C).position v = y := by
  have hnB : 0 < B.data.resolvedWalk.length :=
    B.resolvedWalk_length_pos hxy
  let L := firstSegments B C
  have hL : L ≠ [] := firstSegments_nonempty B C hxy
  let a := L.head hL
  let tail := L.tail
  have hcons : a :: tail = L := List.cons_head_tail hL
  have hchain : (a :: tail).IsChain fun i j =>
      right B C i = left B C j := by
    rw [hcons]
    exact firstSegments_isChain B C
  have hne : ∀ i ∈ a :: tail, left B C i ≠ right B C i := by
    rw [hcons]
    exact firstSegments_ne B C
  have hpair : (a :: tail).Pairwise fun i j =>
      segment ℝ (left B C i) (right B C i) ∩
          segment ℝ (left B C j) (right B C j) ⊆
        {right B C i} := by
    rw [hcons]
    exact firstSegments_pairwise B C
  let D := BrokenLineData.simpleSegmentFamilyChainWalkData
    (left B C) (right B C) a tail hchain hne hpair
  have ha : a = Sum.inl
      (⟨0, hnB⟩ :
        Fin B.data.resolvedWalk.length) := by
    simp only [a, L, firstSegments, List.head_ofFn]
  have hlast : (a :: tail).getLast (by simp) = Sum.inl
      (⟨B.data.resolvedWalk.length - 1, by omega⟩ :
        Fin B.data.resolvedWalk.length) := by
    calc
      (a :: tail).getLast (by simp) = L.getLast hL :=
        List.getLast_congr (by simp) hL hcons
      _ = _ := by
        simpa only [L, firstSegments] using
          (List.getLast_ofFn (f := fun i : Fin B.data.resolvedWalk.length =>
            (Sum.inl i : Address B C)) (firstSegments_nonempty B C hxy))
  refine ⟨_, _, D.path, ?_, ?_, ?_⟩
  · rw [D.range_eq]
    unfold LeanEval.Topology.ClassificationOfSurfaces.Moise.BrokenLineData.resolvedCarrier
    rw [dif_neg hnB.ne']
    rw [hcons]
    ext z
    simp only [Set.mem_iUnion]
    constructor
    · rintro ⟨i, hi, hz⟩
      obtain ⟨j, hj⟩ : ∃ j, Sum.inl j = i := by
        simpa only [L, firstSegments, List.mem_ofFn] using hi
      subst i
      exact ⟨j, hz⟩
    · rintro ⟨i, hz⟩
      refine ⟨Sum.inl i, ?_, hz⟩
      change Sum.inl i ∈ firstSegments B C
      rw [firstSegments, List.mem_ofFn]
      exact ⟨i, rfl⟩
  · rw [BrokenLineData.segmentFamilyLeftVertex_position, ha]
    simp only [left]
    exact B.data.resolvedVertex_start.trans B.start_eq
  · rw [BrokenLineData.segmentFamilyRightVertex_position, hlast]
    simp only [right]
    have hindex :
        (⟨B.data.resolvedWalk.length - 1, by omega⟩ :
          Fin B.data.resolvedWalk.length).succ =
        Fin.last B.data.resolvedWalk.length := by
      apply Fin.ext
      simp only [Fin.val_succ, Fin.val_last]
      omega
    rw [hindex, B.data.resolvedVertex_finish]
    exact B.finish_eq

/-- The second resolved arc becomes a simple graph path in the same common
arrangement, again with its exact resolved carrier. -/
theorem exists_secondPath
    (B : SimpleBrokenLine U x y) (C : SimpleBrokenLine V y x)
    (hxy : x ≠ y) :
    ∃ u v : (complex B C).Vertex,
      ∃ p : (complex B C).vertexGraph.Path u v,
        range ((complex B C).walkGeometricPath p.1) =
            C.data.resolvedCarrier ∧
          (complex B C).position u = y ∧
          (complex B C).position v = x := by
  have hnC : 0 < C.data.resolvedWalk.length :=
    C.resolvedWalk_length_pos hxy.symm
  let L := secondSegments B C
  have hL : L ≠ [] := secondSegments_nonempty B C hxy
  let a := L.head hL
  let tail := L.tail
  have hcons : a :: tail = L := List.cons_head_tail hL
  have hchain : (a :: tail).IsChain fun i j =>
      right B C i = left B C j := by
    rw [hcons]
    exact secondSegments_isChain B C
  have hne : ∀ i ∈ a :: tail, left B C i ≠ right B C i := by
    rw [hcons]
    exact secondSegments_ne B C
  have hpair : (a :: tail).Pairwise fun i j =>
      segment ℝ (left B C i) (right B C i) ∩
          segment ℝ (left B C j) (right B C j) ⊆
        {right B C i} := by
    rw [hcons]
    exact secondSegments_pairwise B C
  let D := BrokenLineData.simpleSegmentFamilyChainWalkData
    (left B C) (right B C) a tail hchain hne hpair
  have ha : a = Sum.inr
      (⟨0, hnC⟩ : Fin C.data.resolvedWalk.length) := by
    simp only [a, L, secondSegments, List.head_ofFn]
  have hlast : (a :: tail).getLast (by simp) = Sum.inr
      (⟨C.data.resolvedWalk.length - 1, by omega⟩ :
        Fin C.data.resolvedWalk.length) := by
    calc
      (a :: tail).getLast (by simp) = L.getLast hL :=
        List.getLast_congr (by simp) hL hcons
      _ = _ := by
        simpa only [L, secondSegments] using
          (List.getLast_ofFn (f := fun i : Fin C.data.resolvedWalk.length =>
            (Sum.inr i : Address B C)) (secondSegments_nonempty B C hxy))
  refine ⟨_, _, D.path, ?_, ?_, ?_⟩
  · rw [D.range_eq]
    unfold LeanEval.Topology.ClassificationOfSurfaces.Moise.BrokenLineData.resolvedCarrier
    rw [dif_neg hnC.ne']
    rw [hcons]
    ext z
    simp only [Set.mem_iUnion]
    constructor
    · rintro ⟨i, hi, hz⟩
      obtain ⟨j, hj⟩ : ∃ j, Sum.inr j = i := by
        simpa only [L, secondSegments, List.mem_ofFn] using hi
      subst i
      exact ⟨j, hz⟩
    · rintro ⟨i, hz⟩
      refine ⟨Sum.inr i, ?_, hz⟩
      change Sum.inr i ∈ secondSegments B C
      rw [secondSegments, List.mem_ofFn]
      exact ⟨i, rfl⟩
  · rw [BrokenLineData.segmentFamilyLeftVertex_position, ha]
    simp only [left]
    exact C.data.resolvedVertex_start.trans C.start_eq
  · rw [BrokenLineData.segmentFamilyRightVertex_position, hlast]
    simp only [right]
    have hindex :
        (⟨C.data.resolvedWalk.length - 1, by omega⟩ :
          Fin C.data.resolvedWalk.length).succ =
        Fin.last C.data.resolvedWalk.length := by
      apply Fin.ext
      simp only [Fin.val_succ, Fin.val_last]
      omega
    rw [hindex, C.data.resolvedVertex_finish]
    exact C.finish_eq

/-- Two resolved polygonal arcs which meet only at their common endpoints
form an exact polygonal circle in their common segment arrangement. -/
theorem exists_polygonalCircle
    (B : SimpleBrokenLine U x y) (C : SimpleBrokenLine V y x)
    (hxy : x ≠ y)
    (hinter : B.data.resolvedCarrier ∩ C.data.resolvedCarrier = {x, y}) :
    ∃ P : PolygonalCircle,
      P.carrier = B.data.resolvedCarrier ∪ C.data.resolvedCarrier := by
  let K := complex B C
  obtain ⟨u, v, p, hpRange, hpu, hpv⟩ := exists_firstPath B C hxy
  obtain ⟨u', v', q, hqRange, hqu, hqv⟩ := exists_secondPath B C hxy
  have hvStart : v = u' := by
    apply K.position_injective
    exact hpv.trans hqu.symm
  have huEnd : u = v' := by
    apply K.position_injective
    exact hpu.trans hqv.symm
  let qWalk : K.vertexGraph.Walk v u := q.1.copy hvStart.symm huEnd.symm
  have hqPath : qWalk.IsPath :=
    (SimpleGraph.Walk.isPath_copy q.1 hvStart.symm huEnd.symm).mpr
      q.property
  let q' : K.vertexGraph.Path v u := ⟨qWalk, hqPath⟩
  have hqRange' : range (K.walkGeometricPath q'.1) =
      C.data.resolvedCarrier := by
    change range (K.walkGeometricPath
      (q.1.copy hvStart.symm huEnd.symm)) = _
    rw [K.range_walkGeometricPath_copy, hqRange]
  have hpathInter : range (K.walkGeometricPath p.1) ∩
      range (K.walkGeometricPath q'.1) =
        {K.position u, K.position v} := by
    rw [hpRange, hqRange', hinter, hpu, hpv]
  have huNeV : u ≠ v := by
    intro huv
    apply hxy
    exact hpu.symm.trans ((congrArg K.position huv).trans hpv)
  have hlong : 1 < p.1.length ∨ 1 < q'.1.length := by
    by_contra hnot
    push Not at hnot
    have hpLe : p.1.length ≤ 1 := hnot.1
    have hqLe : q'.1.length ≤ 1 := hnot.2
    have hpPos : 0 < p.1.length :=
      SimpleGraph.Walk.not_nil_iff_lt_length.mp
        (SimpleGraph.Walk.not_nil_of_ne huNeV)
    have hpOne : p.1.length = 1 := by omega
    have hwalkEq : p.1 = q'.1.reverse := by
      apply SimpleGraph.Walk.eq_of_length_le_one hpLe
      simpa using hqLe
    have hrangeEq : range (K.walkGeometricPath p.1) =
        range (K.walkGeometricPath q'.1) := by
      calc
        range (K.walkGeometricPath p.1) =
            range (K.walkGeometricPath q'.1.reverse) := by rw [hwalkEq]
        _ = range (K.walkGeometricPath q'.1) :=
          Schoenflies.PlaneComplex.range_walkGeometricPath_reverse K q'.1
    have hpEnds : range (K.walkGeometricPath p.1) =
        {K.position u, K.position v} := by
      calc
        range (K.walkGeometricPath p.1) =
            range (K.walkGeometricPath p.1) ∩
              range (K.walkGeometricPath q'.1) := by
                rw [← hrangeEq, inter_self]
        _ = {K.position u, K.position v} := hpathInter
    have hadj : K.vertexGraph.Adj u v :=
      SimpleGraph.Walk.adj_of_length_eq_one hpOne
    have hpEq : p.1 = hadj.toWalk := by
      apply SimpleGraph.Walk.eq_of_length_le_one hpLe
      simp
    have hedge : s(u, v) ∈ p.1.edges := by
      rw [hpEq]
      simp
    let z : Plane := midpoint ℝ (K.position u) (K.position v)
    have hzRange : z ∈ range (K.walkGeometricPath p.1) :=
      Schoenflies.TriangleMesh.PlaneComplex.segment_subset_range_walkGeometricPath_of_mem_edges
        K p.1 hedge (midpoint_mem_segment _ _)
    rw [hpEnds] at hzRange
    have hposNe : K.position u ≠ K.position v := by
      exact fun h => huNeV (K.position_injective h)
    rcases hzRange with hz | hz
    · exact hposNe ((midpoint_eq_left_iff ℝ).mp hz)
    · rw [Set.mem_singleton_iff] at hz
      exact hposNe ((midpoint_eq_right_iff ℝ).mp hz)
  have hcycle : (p.1.append q'.1).IsCycle :=
    BrokenLineData.isCycle_append_of_range_inter_subset_endpoints
      K p q' hpathInter.le hlong
  let P : PolygonalCircle := K.polygonalCircleOfCycle
    (p.1.append q'.1) hcycle
  refine ⟨P, ?_⟩
  dsimp only [P]
  rw [K.polygonalCircleOfCycle_carrier_eq_range_walkGeometricPath,
    K.range_walkGeometricPath_append, hpRange, hqRange']

end TwoArcSegmentFamily

/-- Point-set interface: two injective paths with finite broken-line joins
and endpoint-only overlap have a polygonal circle with exactly their union
as carrier. -/
theorem exists_polygonalCircle_of_two_joined_paths
    {x y : Plane} (hxy : x ≠ y)
    (p : Path x y) (q : Path y x)
    (hp : Injective p) (hq : Injective q)
    (hpq : range p ∩ range q = {x, y})
    (hpJoin : JoinedByBrokenLine (range p) x y)
    (hqJoin : JoinedByBrokenLine (range q) y x) :
    ∃ P : PolygonalCircle, P.carrier = range p ∪ range q := by
  let B := JordanCircle.simpleBrokenLineOfJoined hpJoin
  let C := JordanCircle.simpleBrokenLineOfJoined hqJoin
  have hBPath : range (B.toPath hxy) = range p :=
    JordanCircle.SimpleBrokenLine.range_simpleBrokenLineOfJoined_eq
      p hp hxy hpJoin
  have hCPath : range (C.toPath hxy.symm) = range q :=
    JordanCircle.SimpleBrokenLine.range_simpleBrokenLineOfJoined_eq
      q hq hxy.symm hqJoin
  have hBResolved : B.data.resolvedCarrier = range p := by
    rw [← B.range_toPath hxy, hBPath]
  have hCResolved : C.data.resolvedCarrier = range q := by
    rw [← C.range_toPath hxy.symm, hCPath]
  obtain ⟨P, hP⟩ := TwoArcSegmentFamily.exists_polygonalCircle
    B C hxy (by rw [hBResolved, hCResolved, hpq])
  exact ⟨P, by rw [hP, hBResolved, hCResolved]⟩

end

end Schoenflies
