/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.AuxiliaryJordan
import Submission.Schoenflies.ControlledCrosscuts

/-!
# A polygonal separator frame for a Jordan boundary subarc

This packages the geometric configuration immediately before Moise's finite
separator theorem in Chapter 9.  The auxiliary return path has short endpoint
tails near the selected boundary arc and a compact connected middle.  A fine
outer polygonal frame contains the boundary arc on its inside and the whole
middle of the return path on its outside.
-/

namespace Schoenflies

open Metric Set Function
open LeanEval.Topology.ClassificationOfSurfaces.Moise

namespace JordanCircle
namespace AccessibleAngularArc

variable {J : JordanCircle}

/-- Once the frame contains the wild arc on its inside and avoids the middle
of the auxiliary return path, every intersection with the auxiliary circle
is confined to one of the two endpoint tails. -/
theorem frame_inter_auxiliaryCarrier_subset_tails
    (A : J.AccessibleAngularArc) {s t : unitInterval}
    (P : PolygonalCircle)
    (hArcInside : A.curveArcPlane ⊆ P.interiorRegion)
    (hMiddleDisjoint :
      Disjoint (A.returnPath '' Icc s t) P.carrier) :
    P.carrier ∩ A.auxiliaryJordanCircle.carrier ⊆
      A.returnPath '' Icc (0 : unitInterval) s ∪
        A.returnPath '' Icc t (1 : unitInterval) := by
  intro x hx
  rcases hx with ⟨hxP, hxAux⟩
  rw [A.carrier_auxiliaryJordanCircle] at hxAux
  rcases hxAux with hxArc | ⟨u, rfl⟩
  · have hxInside : x ∈ P.interiorRegion := hArcInside hxArc
    have hxCompl : x ∈ P.carrierᶜ := by
      rw [← P.interior_union_exterior]
      exact Or.inl hxInside
    exact False.elim (hxCompl hxP)
  · rcases le_total u s with hus | hsu
    · left
      exact ⟨u, ⟨bot_le, hus⟩, rfl⟩
    · rcases le_total u t with hut | htu
      · have huMiddle : A.returnPath u ∈
            A.returnPath '' Icc s t :=
          ⟨u, ⟨hsu, hut⟩, rfl⟩
        exact False.elim
          (Set.disjoint_left.mp hMiddleDisjoint huMiddle hxP)
      · right
        exact ⟨u, ⟨htu, le_top⟩, rfl⟩

/-- A frame which puts the boundary arc inside and the middle of the return
path outside must meet both endpoint tails. -/
theorem frame_meets_both_returnTails
    (A : J.AccessibleAngularArc) {s t : unitInterval}
    (P : PolygonalCircle) (hst : s ≤ t)
    (hArcInside : A.curveArcPlane ⊆ P.interiorRegion)
    (hMiddleExterior :
      A.returnPath '' Icc s t ⊆ P.exteriorRegion) :
    (P.carrier ∩
      A.returnPath '' Icc (0 : unitInterval) s).Nonempty ∧
    (P.carrier ∩
      A.returnPath '' Icc t (1 : unitInterval)).Nonempty := by
  have hrightInside :
      A.returnPath (0 : unitInterval) ∈ P.interiorRegion := by
    rw [A.returnPath.source]
    exact hArcInside A.right_mem_curveArcPlane
  have hleftInside :
      A.returnPath (1 : unitInterval) ∈ P.interiorRegion := by
    rw [A.returnPath.target]
    exact hArcInside A.left_mem_curveArcPlane
  have hsExterior : A.returnPath s ∈ P.exteriorRegion :=
    hMiddleExterior ⟨s, ⟨le_rfl, hst⟩, rfl⟩
  have htExterior : A.returnPath t ∈ P.exteriorRegion :=
    hMiddleExterior ⟨t, ⟨hst, le_rfl⟩, rfl⟩
  constructor
  · let first : Set Plane :=
      A.returnPath '' Icc (0 : unitInterval) s
    by_contra hmeet
    have hdisjoint : Disjoint first P.carrier := by
      rw [Set.disjoint_left]
      intro x hxFirst hxP
      exact hmeet ⟨x, hxP, hxFirst⟩
    have hregions : first ⊆
        P.interiorRegion ∪ P.exteriorRegion := by
      rw [P.interior_union_exterior]
      intro x hxFirst hxP
      exact Set.disjoint_left.mp hdisjoint hxFirst hxP
    have hpreconnected : IsPreconnected first :=
      ordConnected_Icc.isPreconnected.image A.returnPath
        A.returnPath.continuous.continuousOn
    rcases hpreconnected.subset_or_subset
        P.isOpen_interiorRegion P.isOpen_exteriorRegion
        P.disjoint_interior_exterior hregions with hInside | hOutside
    · have : A.returnPath s ∈ P.interiorRegion :=
        hInside ⟨s, ⟨bot_le, le_rfl⟩, rfl⟩
      exact Set.disjoint_left.mp P.disjoint_interior_exterior this hsExterior
    · have : A.returnPath (0 : unitInterval) ∈ P.exteriorRegion :=
        hOutside ⟨0, ⟨le_rfl, bot_le⟩, rfl⟩
      exact Set.disjoint_left.mp P.disjoint_interior_exterior hrightInside this
  · let last : Set Plane :=
      A.returnPath '' Icc t (1 : unitInterval)
    by_contra hmeet
    have hdisjoint : Disjoint last P.carrier := by
      rw [Set.disjoint_left]
      intro x hxLast hxP
      exact hmeet ⟨x, hxP, hxLast⟩
    have hregions : last ⊆
        P.interiorRegion ∪ P.exteriorRegion := by
      rw [P.interior_union_exterior]
      intro x hxLast hxP
      exact Set.disjoint_left.mp hdisjoint hxLast hxP
    have hpreconnected : IsPreconnected last :=
      ordConnected_Icc.isPreconnected.image A.returnPath
        A.returnPath.continuous.continuousOn
    rcases hpreconnected.subset_or_subset
        P.isOpen_interiorRegion P.isOpen_exteriorRegion
        P.disjoint_interior_exterior hregions with hInside | hOutside
    · have : A.returnPath t ∈ P.interiorRegion :=
        hInside ⟨t, ⟨le_rfl, le_top⟩, rfl⟩
      exact Set.disjoint_left.mp P.disjoint_interior_exterior this htExterior
    · have : A.returnPath (1 : unitInterval) ∈ P.exteriorRegion :=
        hOutside ⟨1, ⟨le_top, le_rfl⟩, rfl⟩
      exact Set.disjoint_left.mp P.disjoint_interior_exterior hleftInside this

/-- The complete pre-separator configuration in Moise 9.5.

The polygonal frame can be made arbitrarily close to the selected boundary
arc.  Both endpoint tails of the auxiliary return path remain in the requested
neighborhood, whereas its compact connected middle is entirely on the
exterior side of the frame. -/
theorem exists_separatorFrame (A : J.AccessibleAngularArc)
    {epsilon : ℝ} (hepsilon : 0 < epsilon) :
    ∃ (s t : unitInterval) (rho : ℝ)
      (N : FinitePolyhedralNeighborhood A.curveArcPlane
        (thickening rho A.curveArcPlane))
      (P : PolygonalCircle),
      (0 : ℝ) < s ∧ (s : ℝ) < t ∧ (t : ℝ) < 1 ∧
        0 < rho ∧ rho ≤ epsilon ∧
        A.returnPath '' Icc (0 : unitInterval) s ⊆
          thickening epsilon A.curveArcPlane ∧
        A.returnPath '' Icc t (1 : unitInterval) ⊆
          thickening epsilon A.curveArcPlane ∧
        P.carrier ⊆ thickening rho A.curveArcPlane ∧
        A.curveArcPlane ⊆ P.interiorRegion ∧
        A.returnPath '' Icc s t ⊆ P.exteriorRegion ∧
        IsCompact (A.returnPath '' Icc s t) ∧
        IsPreconnected (A.returnPath '' Icc s t) ∧
        Disjoint (A.returnPath '' Icc s t) P.carrier ∧
        (P.carrier ∩
          A.returnPath '' Icc (0 : unitInterval) s).Nonempty ∧
        (P.carrier ∩
          A.returnPath '' Icc t (1 : unitInterval)).Nonempty ∧
        P.carrier ∩ A.auxiliaryJordanCircle.carrier ⊆
          A.returnPath '' Icc (0 : unitInterval) s ∪
            A.returnPath '' Icc t (1 : unitInterval) := by
  obtain ⟨s, t, hspos, hst, htone, hfirst, hlast,
      hmiddleCompact, hmiddlePreconnected, _hmiddleInside, hmiddleArc⟩ :=
    A.exists_returnPath_cuts hepsilon
  let middle : Set Plane := A.returnPath '' Icc s t
  obtain ⟨delta, hdelta, hmiddleThick⟩ :=
    A.exists_thickening_disjoint_of_compact hmiddleCompact hmiddleArc
  let eta : ℝ := min epsilon delta
  have heta : 0 < eta := lt_min hepsilon hdelta
  have hetaEpsilon : eta ≤ epsilon := min_le_left _ _
  have hetaDelta : eta ≤ delta := min_le_right _ _
  have hstLe : s ≤ t := by
    change (s : ℝ) ≤ (t : ℝ)
    exact hst.le
  have hsMiddle : A.returnPath s ∈ middle :=
    ⟨s, ⟨le_rfl, hstLe⟩, rfl⟩
  have hsNotArc : A.returnPath s ∉ A.curveArcPlane := by
    intro hsArc
    exact Set.disjoint_left.mp hmiddleArc hsMiddle hsArc
  obtain ⟨rho, N, P, hrho, hrhoEta, hPthick,
      hArcInside, hsExterior⟩ :=
    A.exists_outerFrame_with_point_exterior heta hsNotArc
  have hrhoEpsilon : rho ≤ epsilon := hrhoEta.trans hetaEpsilon
  have hrhoDelta : rho ≤ delta := hrhoEta.trans hetaDelta
  have hmiddleP : Disjoint middle P.carrier := by
    apply hmiddleThick.mono_right
    exact hPthick.trans (thickening_mono hrhoDelta A.curveArcPlane)
  have hmiddleRegions : middle ⊆
      P.interiorRegion ∪ P.exteriorRegion := by
    rw [P.interior_union_exterior]
    intro x hxMiddle hxCarrier
    exact Set.disjoint_left.mp hmiddleP hxMiddle hxCarrier
  have hmiddleExterior : middle ⊆ P.exteriorRegion := by
    rcases hmiddlePreconnected.subset_or_subset
        P.isOpen_interiorRegion P.isOpen_exteriorRegion
        P.disjoint_interior_exterior hmiddleRegions with hInside | hOutside
    · have hsInside : A.returnPath s ∈ P.interiorRegion := hInside hsMiddle
      exact False.elim
        (Set.disjoint_left.mp P.disjoint_interior_exterior hsInside hsExterior)
    · exact hOutside
  have hmeets :=
    A.frame_meets_both_returnTails P hstLe hArcInside hmiddleExterior
  have hintersections :=
    A.frame_inter_auxiliaryCarrier_subset_tails P hArcInside hmiddleP
  exact ⟨s, t, rho, N, P, hspos, hst, htone, hrho, hrhoEpsilon,
    hfirst, hlast, hPthick, hArcInside, hmiddleExterior,
    hmiddleCompact, hmiddlePreconnected, hmiddleP,
    hmeets.1, hmeets.2, hintersections⟩

end AccessibleAngularArc
end JordanCircle

end Schoenflies
