/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.CompatibleShrinkingMoiseDiskStages

/-!
# Exhaustion of the Jordan inside by the shrinking source disks

Every point of the open Jordan inside lies in the interior of some retained
shrinking source disk.  The proof joins the point to a fixed point of the
first disk by a path in the inside; the path keeps a positive distance from
the Jordan curve, while sufficiently late source carriers lie in an
arbitrarily thin closed neighborhood of the curve, so some late carrier
misses the path entirely.  Connectedness then forces the whole path, and in
particular the requested point, into the interior region of that stage.
-/

namespace Schoenflies

open Metric Set Function
open LeanEval.Topology.ClassificationOfSurfaces.Moise

noncomputable section

namespace JordanCircle.InitialAngularArcs

variable {J : JordanCircle} (I : J.InitialAngularArcs)

/-- The fixed basepoint lies in the interior of every retained stage. -/
theorem mem_shrinkingCompatibleStageSourceDisk_interiorRegion_of_first
    {y : Plane}
    (hy : y ∈ (I.shrinkingCompatibleStageSourceDisk 0).interiorRegion)
    (n : ℕ) :
    y ∈ (I.shrinkingCompatibleStageSourceDisk n).interiorRegion := by
  cases n with
  | zero => exact hy
  | succ m =>
      apply I.shrinkingCompatibleStageSourceDisk_strictlyNested m
      apply I.shrinkingCompatibleStageSourceDisk_closedRegion_mono
        (Nat.zero_le m)
      rw [(I.shrinkingCompatibleStageSourceDisk 0).closedRegion_eq_union]
      exact Or.inl hy

/-- **Source exhaustion.**  Every point of the Jordan inside lies in the
interior region of some retained shrinking source disk. -/
theorem exists_mem_shrinkingCompatibleStageSourceDisk_interiorRegion
    {x : Plane} (hx : x ∈ J.inside) :
    ∃ n : ℕ,
      x ∈ (I.shrinkingCompatibleStageSourceDisk n).interiorRegion := by
  -- a basepoint deep inside the first retained disk
  obtain ⟨y, hy⟩ :=
    (I.shrinkingCompatibleStageSourceDisk 0).isConnected_interiorRegion.nonempty
  have hyInside : y ∈ J.inside := by
    apply I.shrinkingCompatibleStageSourceDisk_closedRegion_subset_inside 0
    rw [(I.shrinkingCompatibleStageSourceDisk 0).closedRegion_eq_union]
    exact Or.inl hy
  -- a path from the basepoint to the requested point inside the region
  have hpathConn : IsPathConnected J.inside :=
    (J.inside_isOpen.isConnected_iff_isPathConnected).mp J.inside_isConnected
  obtain ⟨γ, hγ⟩ := hpathConn.joinedIn y hyInside x hx
  set K : Set Plane := range γ with hK_def
  have hKcompact : IsCompact K := isCompact_range γ.continuous
  have hKconn : IsPreconnected K := isPreconnected_range γ.continuous
  have hKsubset : K ⊆ J.inside := by
    rintro z ⟨t, rfl⟩
    exact hγ t
  have hyK : y ∈ K := ⟨0, γ.source⟩
  have hxK : x ∈ K := ⟨1, γ.target⟩
  -- the path is separated from the Jordan curve by a positive thickening
  have hKdisj : Disjoint K J.carrier :=
    Set.disjoint_left.mpr fun z hz =>
      J.inside_subset_compl (hKsubset hz)
  have hCclosed : IsClosed J.carrier :=
    (isCompact_range J.continuous).isClosed
  obtain ⟨δ, hδpos, hthick⟩ := hKdisj.exists_thickenings hKcompact hCclosed
  -- a late stage whose carrier lives inside that thickening of the curve
  obtain ⟨N, hN⟩ :=
    I.eventually_shrinkingCompatibleStageSourceDisk_carrier_subset_cthickening
      (half_pos hδpos)
  have hcarrierThin :
      (I.shrinkingCompatibleStageSourceDisk N).carrier ⊆
        thickening δ J.carrier :=
    (hN N le_rfl).trans
      (cthickening_subset_thickening' hδpos (half_lt_self hδpos) J.carrier)
  have hKavoid : ∀ z ∈ K,
      z ∉ (I.shrinkingCompatibleStageSourceDisk N).carrier := by
    intro z hz hzc
    exact Set.disjoint_left.mp hthick
      (self_subset_thickening hδpos K hz) (hcarrierThin hzc)
  -- connectedness selects the interior side of the late polygonal circle
  have hcover : K ⊆
      (I.shrinkingCompatibleStageSourceDisk N).interiorRegion ∪
        ((I.shrinkingCompatibleStageSourceDisk N).closedRegion)ᶜ := by
    intro z hz
    by_cases hzc : z ∈ (I.shrinkingCompatibleStageSourceDisk N).closedRegion
    · left
      rw [(I.shrinkingCompatibleStageSourceDisk N).closedRegion_eq_union]
        at hzc
      exact hzc.resolve_right (hKavoid z hz)
    · exact Or.inr hzc
  have hdisjSides :
      Disjoint (I.shrinkingCompatibleStageSourceDisk N).interiorRegion
        ((I.shrinkingCompatibleStageSourceDisk N).closedRegion)ᶜ := by
    rw [Set.disjoint_compl_right_iff_subset,
      (I.shrinkingCompatibleStageSourceDisk N).closedRegion_eq_union]
    exact subset_union_left
  rcases hKconn.subset_or_subset
      (I.shrinkingCompatibleStageSourceDisk N).isOpen_interiorRegion
      ((I.shrinkingCompatibleStageSourceDisk
        N).isCompact_closedRegion.isClosed.isOpen_compl)
      hdisjSides hcover with hint | hext
  · exact ⟨N, hint hxK⟩
  · exact absurd
      ((I.shrinkingCompatibleStageSourceDisk N).closedRegion_eq_union ▸
        (Or.inl (I.mem_shrinkingCompatibleStageSourceDisk_interiorRegion_of_first
          hy N) :
          y ∈ (I.shrinkingCompatibleStageSourceDisk N).interiorRegion ∪
            (I.shrinkingCompatibleStageSourceDisk N).carrier))
      (fun h => hext hyK h)

/-- Monotone form of the exhaustion: from the found stage onward the point
stays in every later interior region. -/
theorem eventually_mem_shrinkingCompatibleStageSourceDisk_interiorRegion
    {x : Plane} (hx : x ∈ J.inside) :
    ∃ N : ℕ, ∀ n : ℕ, N ≤ n →
      x ∈ (I.shrinkingCompatibleStageSourceDisk n).interiorRegion := by
  obtain ⟨N, hN⟩ :=
    I.exists_mem_shrinkingCompatibleStageSourceDisk_interiorRegion hx
  refine ⟨N, ?_⟩
  intro n hn
  induction n, hn using Nat.le_induction with
  | base => exact hN
  | succ n hNn ih =>
      apply I.shrinkingCompatibleStageSourceDisk_strictlyNested n
      rw [(I.shrinkingCompatibleStageSourceDisk n).closedRegion_eq_union]
      exact Or.inl ih

end JordanCircle.InitialAngularArcs

end

end Schoenflies
