/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
import Submission.Schoenflies.MarkedMoiseBandGluing
import Submission.Schoenflies.ShrinkingMoiseBandCells

/-!
# Homeomorphisms of the shrinking recursive Moise bands

The finite marked-cell gluing theorem applies uniformly to every sufficiently
late band in the recursively shrinking collar sequence.  This file records
that specialization while retaining the exact formula on each shrinking
cell; the latter is the metric control used at the original Jordan boundary.
-/

namespace Schoenflies

open Set
open LeanEval.Topology.ClassificationOfSurfaces.Moise
open StandardPolygonalCollars

noncomputable section

namespace JordanCircle.InitialAngularArcs

variable {J : JordanCircle} (I : J.InitialAngularArcs)

/-- Every sufficiently late shrinking Moise band is homeomorphic to any
chosen consecutive standard radial shell. -/
theorem eventually_shrinkingMoiseBandHomeomorph :
    ∃ N : ℕ, ∀ k : ℕ, N ≤ k → ∀ m : ℕ,
      let L₀ := I.nextInsideCollarLater k
        (I.shrinkingInsideCollarStage k)
      let S₁ := InsideCollarStage.ofLater I
        (I.shrinkingInsideCollarStage k) L₀
      let L₁ := I.nextInsideCollarLater (k + 1) S₁
      Nonempty
        (PolygonalCircle.closedShell L₀.next.circle L₁.next.circle ≃ₜ
          PolygonalCircle.closedShell (disk m) (disk (m + 1))) := by
  obtain ⟨N, hN⟩ :=
    I.eventually_shrinkingMoiseBand_parentClosedRegion_inter
  refine ⟨N, ?_⟩
  intro k hk m
  dsimp only
  let S₀ := I.shrinkingInsideCollarStage k
  let L₀ := I.nextInsideCollarLater k S₀
  let S₁ := InsideCollarStage.ofLater I S₀ L₀
  let L₁ := I.nextInsideCollarLater (k + 1) S₁
  exact ⟨L₁.markedMoiseBandHomeomorph m (hN k hk)⟩

/-- A stable choice of an index after which every shrinking band has the
outward side orientation required by marked cell gluing. -/
def shrinkingMoiseBandStartIndex : ℕ := by
  classical
  exact Nat.find I.eventually_shrinkingMoiseBand_parentClosedRegion_inter

theorem shrinkingMoiseBandStartIndex_spec
    (k : ℕ) (hk : I.shrinkingMoiseBandStartIndex ≤ k) :
    ∀ a : LevelAddress
      (I.nextInsideCollarLater k
        (I.shrinkingInsideCollarStage k)).next.level,
    let L₀ := I.nextInsideCollarLater k
      (I.shrinkingInsideCollarStage k)
    let S₁ := InsideCollarStage.ofLater I
      (I.shrinkingInsideCollarStage k) L₀
    let L₁ := I.nextInsideCollarLater (k + 1) S₁
    L₀.next.circle.closedRegion ∩
        (L₁.moiseBandPolygonalCircle a).closedRegion =
      range
        (L₀.next.family.forgetObstacle.synchronizedCrosscutPath a) := by
  classical
  exact (Nat.find_spec
    I.eventually_shrinkingMoiseBand_parentClosedRegion_inter) k hk

/-- The marked homeomorphism of source band `k` onto standard shell `m`,
using the canonical eventual-orientation threshold. -/
def shrinkingMoiseBandHomeomorph
    (k : ℕ) (hk : I.shrinkingMoiseBandStartIndex ≤ k) (m : ℕ) :
    let L₀ := I.nextInsideCollarLater k
      (I.shrinkingInsideCollarStage k)
    let S₁ := InsideCollarStage.ofLater I
      (I.shrinkingInsideCollarStage k) L₀
    let L₁ := I.nextInsideCollarLater (k + 1) S₁
    PolygonalCircle.closedShell L₀.next.circle L₁.next.circle ≃ₜ
      PolygonalCircle.closedShell (disk m) (disk (m + 1)) := by
  dsimp only
  let S₀ := I.shrinkingInsideCollarStage k
  let L₀ := I.nextInsideCollarLater k S₀
  let S₁ := InsideCollarStage.ofLater I S₀ L₀
  let L₁ := I.nextInsideCollarLater (k + 1) S₁
  exact L₁.markedMoiseBandHomeomorph m
    (I.shrinkingMoiseBandStartIndex_spec k hk)

/-- The sequence-specialized band map retains the exact marked-cell formula
needed for the uniform shrinking argument. -/
theorem shrinkingMoiseBandHomeomorph_apply_cell
    (k : ℕ) (hk : I.shrinkingMoiseBandStartIndex ≤ k) (m : ℕ)
    (a : LevelAddress
      (I.nextInsideCollarLater k
        (I.shrinkingInsideCollarStage k)).next.level)
    {x : Plane}
    (hxShell : x ∈
      PolygonalCircle.closedShell
        (I.shrinkingInsideCollarStage (k + 1)).circle
        (I.shrinkingInsideCollarStage (k + 2)).circle)
    (hxCell :
      let L₀ := I.nextInsideCollarLater k
        (I.shrinkingInsideCollarStage k)
      let S₁ := InsideCollarStage.ofLater I
        (I.shrinkingInsideCollarStage k) L₀
      let L₁ := I.nextInsideCollarLater (k + 1) S₁
      x ∈ (L₁.moiseBandPolygonalCircle a).closedRegion) :
    (I.shrinkingMoiseBandHomeomorph k hk m ⟨x, hxShell⟩ : Plane) =
      let L₀ := I.nextInsideCollarLater k
        (I.shrinkingInsideCollarStage k)
      let S₁ := InsideCollarStage.ofLater I
        (I.shrinkingInsideCollarStage k) L₀
      let L₁ := I.nextInsideCollarLater (k + 1) S₁
      (L₁.markedMoiseCellHomeomorph m a ⟨x, hxCell⟩ : Plane) := by
  dsimp only at hxCell ⊢
  let S₀ := I.shrinkingInsideCollarStage k
  let L₀ := I.nextInsideCollarLater k S₀
  let S₁ := InsideCollarStage.ofLater I S₀ L₀
  let L₁ := I.nextInsideCollarLater (k + 1) S₁
  exact L₁.markedMoiseBandHomeomorph_apply m
    (I.shrinkingMoiseBandStartIndex_spec k hk) a hxShell hxCell

end JordanCircle.InitialAngularArcs

end

end Schoenflies
