/-
This file is generated by port_submission.py.  Edit the source module instead,
then run `python3 port_submission.py` from the repository root.
-/
/-
Copyright (c) 2026 ClassificationOfSurfaces contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ClassificationOfSurfaces contributors
-/
import Submission.ClassificationOfSurfaces.CellComplex
import Mathlib.Data.Fintype.EquivFin

/-!
# Finite signed-dart presentations

This file removes arbitrary dart names from a finite surface cell complex. Unoriented edges are
the quotient of darts by orientation reversal. When reversal has no fixed points, choosing one
orientation in each orbit identifies all darts with signed orbit names, and a final finite
relabeling gives names in `Fin`.

The construction uses only `Dart`, `inv`, finiteness, and the involution laws. In particular it
does not trust the stored vertex endpoints. This is the combinatorial input needed before cyclic
boundary-word moves can be stated independently of a presentation's original edge names.
-/

namespace LeanEval
namespace Topology
namespace ClassificationOfSurfaces
namespace SurfaceCellComplex

namespace SignedDart

/-- Relabel signed darts along an equivalence of edge names. -/
def mapEquiv {α β : Type*} (e : α ≃ β) : SignedDart α ≃ SignedDart β where
  toFun
    | .pos a => .pos (e a)
    | .neg a => .neg (e a)
  invFun
    | .pos b => .pos (e.symm b)
    | .neg b => .neg (e.symm b)
  left_inv := by
    intro d
    cases d <;> simp
  right_inv := by
    intro d
    cases d <;> simp

@[simp]
theorem mapEquiv_pos {α β : Type*} (e : α ≃ β) (a : α) :
    mapEquiv e (.pos a) = .pos (e a) :=
  rfl

@[simp]
theorem mapEquiv_neg {α β : Type*} (e : α ≃ β) (a : α) :
    mapEquiv e (.neg a) = .neg (e a) :=
  rfl

@[simp]
theorem mapEquiv_flip {α β : Type*} (e : α ≃ β) (d : SignedDart α) :
    mapEquiv e d.flip = (mapEquiv e d).flip := by
  cases d <;> rfl

end SignedDart

/-- The equivalence relation on darts generated by reversing orientation. -/
def edgeSetoid (K : SurfaceCellComplex) : Setoid K.Dart where
  r := K.SameEdge
  iseqv := {
    refl := fun _ ↦ Or.inl rfl
    symm := by
      intro d e h
      rcases h with rfl | h
      · exact Or.inl rfl
      · right
        rw [h, K.inv_involutive]
    trans := by
      intro d e f hde hef
      rcases hde with rfl | hde
      · exact hef
      · rcases hef with rfl | hef
        · exact Or.inr hde
        · left
          rw [hef, hde, K.inv_involutive]
  }

/-- Unoriented edges are inverse-dart orbits. -/
abbrev EdgeOrbit (K : SurfaceCellComplex) :=
  Quotient K.edgeSetoid

/-- The unoriented edge containing a dart. -/
def edgeOrbit (K : SurfaceCellComplex) (d : K.Dart) : K.EdgeOrbit :=
  Quotient.mk K.edgeSetoid d

@[simp]
theorem edgeOrbit_eq_iff (K : SurfaceCellComplex) (d e : K.Dart) :
    K.edgeOrbit d = K.edgeOrbit e ↔ K.SameEdge d e :=
  @Quotient.eq _ K.edgeSetoid d e

@[simp]
theorem edgeOrbit_inv (K : SurfaceCellComplex) (d : K.Dart) :
    K.edgeOrbit (K.inv d) = K.edgeOrbit d := by
  exact @Quotient.sound _ K.edgeSetoid _ _ (Or.inr (K.inv_involutive d).symm)

noncomputable instance edgeOrbitFintype (K : SurfaceCellComplex) : Fintype K.EdgeOrbit :=
  Fintype.ofFinite _

private noncomputable def edgeRepresentative
    (K : SurfaceCellComplex) (e : K.EdgeOrbit) : K.Dart :=
  Quotient.out e

@[simp]
private theorem edgeOrbit_representative
    (K : SurfaceCellComplex) (e : K.EdgeOrbit) :
    K.edgeOrbit (K.edgeRepresentative e) = e :=
  Quotient.out_eq e

private noncomputable def signedDartToDart (K : SurfaceCellComplex) :
    SignedDart K.EdgeOrbit → K.Dart
  | .pos e => K.edgeRepresentative e
  | .neg e => K.inv (K.edgeRepresentative e)

@[simp]
private theorem signedDartToDart_flip
    (K : SurfaceCellComplex) (d : SignedDart K.EdgeOrbit) :
    K.signedDartToDart d.flip = K.inv (K.signedDartToDart d) := by
  cases d <;> simp [signedDartToDart, SignedDart.flip, K.inv_involutive]

private theorem signedDartToDart_surjective (K : SurfaceCellComplex) :
    Function.Surjective K.signedDartToDart := by
  intro d
  have hrel :
      K.SameEdge (K.edgeRepresentative (K.edgeOrbit d)) d :=
    @Quotient.mk_out _ K.edgeSetoid d
  rcases hrel with h | h
  · exact ⟨.pos (K.edgeOrbit d), by simpa only [signedDartToDart] using h.symm⟩
  · exact ⟨.neg (K.edgeOrbit d), by simpa only [signedDartToDart] using h.symm⟩

private theorem signedDartToDart_injective
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) :
    Function.Injective K.signedDartToDart := by
  intro d e hde
  cases d with
  | pos d =>
      cases e with
      | pos e =>
          congr 1
          calc
            d = K.edgeOrbit (K.edgeRepresentative d) := (K.edgeOrbit_representative d).symm
            _ = K.edgeOrbit (K.edgeRepresentative e) := congrArg K.edgeOrbit hde
            _ = e := K.edgeOrbit_representative e
      | neg e =>
          have horbit : d = e := by
            calc
              d = K.edgeOrbit (K.edgeRepresentative d) := (K.edgeOrbit_representative d).symm
              _ = K.edgeOrbit (K.inv (K.edgeRepresentative e)) := congrArg K.edgeOrbit hde
              _ = e := by simp
          subst e
          apply False.elim
          apply hinv (K.edgeRepresentative d)
          simpa only [signedDartToDart] using hde.symm
  | neg d =>
      cases e with
      | pos e =>
          have horbit : d = e := by
            calc
              d = K.edgeOrbit (K.inv (K.edgeRepresentative d)) := by simp
              _ = K.edgeOrbit (K.edgeRepresentative e) := congrArg K.edgeOrbit hde
              _ = e := K.edgeOrbit_representative e
          subst e
          apply False.elim
          apply hinv (K.edgeRepresentative d)
          simpa only [signedDartToDart] using hde
      | neg e =>
          congr 1
          calc
            d = K.edgeOrbit (K.edgeRepresentative d) := (K.edgeOrbit_representative d).symm
            _ = K.edgeOrbit (K.edgeRepresentative e) :=
              congrArg K.edgeOrbit (K.inv.injective hde)
            _ = e := K.edgeOrbit_representative e

/-- A fixed-point-free involution presents the darts as signed unoriented edges. -/
noncomputable def signedDartEquiv
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) :
    SignedDart K.EdgeOrbit ≃ K.Dart :=
  Equiv.ofBijective K.signedDartToDart
    ⟨K.signedDartToDart_injective hinv, K.signedDartToDart_surjective⟩

@[simp]
theorem signedDartEquiv_symm_inv
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) (d : K.Dart) :
    (K.signedDartEquiv hinv).symm (K.inv d) =
      ((K.signedDartEquiv hinv).symm d).flip := by
  apply (K.signedDartEquiv hinv).injective
  rw [Equiv.apply_symm_apply]
  change _ = K.signedDartToDart (((K.signedDartEquiv hinv).symm d).flip)
  rw [K.signedDartToDart_flip]
  exact (congrArg K.inv ((K.signedDartEquiv hinv).apply_symm_apply d)).symm

/-- The number of unoriented edges, computed as the number of inverse-dart orbits. -/
noncomputable def numEdgeOrbits (K : SurfaceCellComplex) : ℕ :=
  Fintype.card K.EdgeOrbit

/-- Relabel arbitrary darts as signed `Fin`-labelled unoriented edges. -/
noncomputable def finSignedDartEquiv
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) :
    K.Dart ≃ SignedDart (Fin K.numEdgeOrbits) :=
  (K.signedDartEquiv hinv).symm.trans
    (SignedDart.mapEquiv (Fintype.equivFin K.EdgeOrbit))

@[simp]
theorem finSignedDartEquiv_inv
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) (d : K.Dart) :
    K.finSignedDartEquiv hinv (K.inv d) =
      (K.finSignedDartEquiv hinv d).flip := by
  simp [finSignedDartEquiv]

/-- A face boundary with its arbitrary dart names replaced by signed finite edge labels. -/
noncomputable def normalizedBoundary
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) (f : K.Face) :
    List (SignedDart (Fin K.numEdgeOrbits)) :=
  (K.boundary f).map (K.finSignedDartEquiv hinv)

@[simp]
theorem normalizedBoundary_length
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) (f : K.Face) :
    (K.normalizedBoundary hinv f).length = K.faceBoundaryLength f := by
  simp [normalizedBoundary, faceBoundaryLength]

/-- Finite relabeling loses no information from a face boundary. -/
theorem normalizedBoundary_map_symm
    (K : SurfaceCellComplex) (hinv : ∀ d, K.inv d ≠ d) (f : K.Face) :
    (K.normalizedBoundary hinv f).map (K.finSignedDartEquiv hinv).symm =
      K.boundary f := by
  simp [normalizedBoundary]

end SurfaceCellComplex
end ClassificationOfSurfaces
end Topology
end LeanEval
